### ISSUE TITLE
View is saved before ProcessView job is ran

### ISSUE THREAD

**Issue by BobbyBorisov** [cyrildewit/eloquent-viewable#101]
- Eloquent Viewable: 2.3.0
- Laravel Version: 5.6
- PHP Version: 7.2.8
- Database Driver & Version: mysql:5.7

### Description:
First of all thanks for the cool package! I have the following problem. I am trying to save page views my resource and it worked like a charm, But then i saw that i can dispatch a job in order to offload the server and I configured it in the eloquent-viewable file

### Steps To Reproduce:

0. configure queues and set eloquent_viewable.jobs.store_new_view.enabled = true
1. use addViewWithExpiryDate(Carbon::now()->addMinute());
2. observe the database table views
3. record is added for the page view despite the fact it is configured to first dispatch a job
3. job is actually in the table and it is ran after the configured delay in the eloquent-viewable config

#### Expected behavior:

I expect page view no to be saved before job is ran

#### Actual behavior:

Page view is saved before the job ran

**Comment by Mohammad-Alavi** [comment]
I have the same problem 🤔 any news on this one? 🤔

**Comment by cyrildewit** [comment]
Which queue driver are you using?

**Comment by BobbyBorisov** [comment]
I am using database @cyrildewit

**Comment by davodsaraei** [comment]
@cyrildewit Hi, I have the same issue.
I think you must change 201 line of ViewableService.php as a bellow
`$view = app(ViewContract::class)->fill([`

**Comment by cyrildewit** [comment]
@davodsaraei thank you for digging into the code. Yes you're right. `->create` saves the view immediately, instead of just creating an object. I released `v2.4.1` with a fix.
