### ISSUE TITLE
Support for Laravel 5.7

### ISSUE THREAD

**Issue by iamsrikanthgopi** [cyrildewit/eloquent-viewable#102]
Does this package support the latest laravel 5.7 version?

I'm unable to install and see a lot of errors regarding dependencies for laravel 5.6

Kindly update at the earliest

**Comment by cyrildewit** [comment]
> Does this package support the latest laravel 5.7 version?

At the moment not. I was waiting for the official announcement.

I will take a look at it as fast as possible.

Thank you for notifying me!

**Comment by cyrildewit** [comment]
@iamsrikanthgopi I released a new major version (`v3.0.0`) with Laravel 5.7 support.
