### ISSUE TITLE
laravel 5.7 support

### ISSUE THREAD

**Issue by avasiliev87** [cyrildewit/eloquent-viewable#103]
Does it support for laravel 5.7?
I see following error messages when I was trying to laravel version to latest
    
- Conclusion: don't install laravel/framework v5.7.2
- Installation request for cyrildewit/eloquent-viewable 4.* -> satisfiable by cyrildewit/eloquent-viewable[4.0.x-dev].
- Conclusion: don't install laravel/framework v5.7.1

**Comment by cyrildewit** [comment]
I released `v2.4.0` with Laravel 5.7 support!

**Comment by avasiliev87** [comment]
great, thanks!
