### ISSUE TITLE
orderByViewsCount week?

### ISSUE THREAD

**Issue by madroot** [cyrildewit/eloquent-viewable#108]
You have the "orderByViewsCount" feature, but how can I get the most viewed posts in the last week?

**Comment by cyrildewit** [comment]
@madroot sorry for the late response. I had the following concept in mind for `v3` (and `v2` if it's not a breaking change and if it doesn't take too much time):

```php
// Post::orderByViewsCount($order, $period);
Post::orderByViewsCount('asc', Period::pastWeeks(1));
Post::orderByViewsCount('desc', Period::pastWeeks(1));
```

```php
Post::orderByViews('asc', Period::pastWeeks(1));
Post::orderByViews('desc', Period::pastWeeks(1));
```
