### ISSUE TITLE
How to get Most Viewed posts in last week?

### ISSUE THREAD

**Issue by arifulhb** [cyrildewit/eloquent-viewable#110]
Hi, 

This package seems very useful, but I guess documentation seems lacking few issues as well.

1. My first question is, Is there any way to get most viewed posts in last week?
2. My Queue Driver is set to `redis` and planned to moved to `SQS` when I deploy the app in production. But what else I need to do to if I set `enable = true` in `store_new_view`?

Thanks
Ariful

**Comment by cyrildewit** [comment]
Hey @arifulhb,

**Regarding question one**

Yes, there is but not out of the box. You will have to implement this yourself. It's an upcoming feature for `v3`.

**Comment by cyrildewit** [comment]
**Regarding question two**

Nothing, once setted to true, every view will be queued.

**Comment by cyrildewit** [comment]
Closing this issue, because the feature you (kinda) requested in question one is already requested in #108
