### ISSUE TITLE
Job Failed

### ISSUE THREAD

**Issue by cromartie1984** [cyrildewit/eloquent-viewable#112]
I wanted to add the view to the jobs queue, but this last one failed.
Here's my stack trace  :

`Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [CyrildeWit\EloquentViewable\View]. in /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:414
Stack trace:
#0 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(85): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(55): CyrildeWit\EloquentViewable\Jobs\ProcessView->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
#2 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(45): CyrildeWit\EloquentViewable\Jobs\ProcessView->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#3 [internal function]: CyrildeWit\EloquentViewable\Jobs\ProcessView->__wakeup()
#4 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(42): unserialize('O:44:"CyrildeWi...')
#5 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#6 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(326): Illuminate\Queue\Jobs\Job->fire()
#7 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(276): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#8 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#9 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#10 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#11 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#12 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\Container\Container->call(Array)
#17 /var/www/html/d3mystic/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /var/www/html/d3mystic/vendor/symfony/console/Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/d3mystic/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/d3mystic/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/d3mystic/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/d3mystic/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}`

Any ideas?

**Comment by dungnh** [comment]
I got same this issue, please help

**Comment by haleyngonadi** [comment]
Same here :(

**Comment by cyrildewit** [comment]
_Sorry for the delay. I'm pretty busy with school, jobs and sport right now.__

Hey @cromartie1984,

Thanks for reporting this issue and providing a stacktrace. I might know why this error is appearing. The job class uses the `SerializesModels`. This trait should only be used when the constructor only accepts saved models, because it will save the primary id instead of the whole model. But since this package passes an unsaved model (the new view) to the constructor of the job, executing the job at a later time will fail, because the data gets lost.

**Comment by haleyngonadi** [comment]
@cyrildewit Thanks for responding to us! What can we do now?

**Comment by cyrildewit** [comment]
@haleyngonadi I'm working on it. Releasing a fix soon!

**Comment by cyrildewit** [comment]
@cromartie1984 @dungnh @haleyngonadi I released `v2.4.2` with a fix. It removes the `SerializesModels` trait from the `ProcessView` job. Can one of you confirm if this issue is solved? Thanks!
