### ISSUE TITLE
[Feature Request] Models with similar visitors

### ISSUE THREAD

**Issue by Livijn** [cyrildewit/eloquent-viewable#122]
I think it would be nice to have a feature that returned a list of objects that has similar visitors. This is how I implemented it for myself, so you could take some inspiration from here. It would be better if this was an actual relationship though, so you could eager load it.

    /**
     * @param int $amount
     * @return Ad[]|\Illuminate\Database\Eloquent\Collection
     */
    public function adsWithSimilarVistors($amount = 5)
    {
        $visitors = $this->views->pluck('visitor');
        
        return Ad::with(['user'])
            ->where('id', '!=', $this->id)
            ->whereHas('views', function ($query) use ($visitors) {
                $query->whereIn('visitor', $visitors);
            })
            ->take($amount)
            ->get();
    }

**Comment by cyrildewit** [comment]
@Livijn I needed a little bit of time to think about, but I don't want to add this feature this right now. It looks pretty cool and useful, but I think it's a very specific requirement and once I add it to the core I will need to maintain it.

If other people are also requesting this feature, I might consider adding it to `v4` or up.

Thanks for the suggestion!
