### ISSUE TITLE
String data, right truncated

### ISSUE THREAD

**Issue by zymawy** [cyrildewit/eloquent-viewable#123]
- Eloquent Viewable: ^2.4.3
- Laravel Version:5.7.15
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:
Suddly, This Error Rised, 
It Seems That Value Being Insreted To The `vistor` Column Is Bigger Than The Column Type. 
Any Light On This?
### Steps To Reproduce:

```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'visitor' at row 1 (SQL: insert into `views` (`viewable_id`, `viewable_type`, `visitor`, `viewed_at`, `updated_at`, `created_at`) values (1, App\Institute, eyJpdiI6IjdhUVRMOUQxTlpTUG1MaUhOanMxc1E9PSIsInZhbHVlIjoibGx0elwvSGRkUHZtUGgrZHF5cHcrMm1pU1ppazBOM0pUZStnbURaTHNQdHFBR2p1cjdSMlZxaU1CcG5kNU9iQktDeUdsWmx2NVZTMlRWck1zTG41aWo3dHRTYXAzTFhScFVHR1IxUU1BRW52YWNkNEhGb1l2S3dsVEhGbUN5OHFQIiwibWFjIjoiOGMwY2NlMDI1YTBlMjQyNjYxOTEzMDcyM2Q0MDZiMTk5ZjUwNGJiOTUzNDAxOGYzNzUzZWE2Mzk1MTA1YzY3ZSJ9, 2018-11-29 22:08:07, 2018-11-29 22:08:07, 2018-11-29 22:08:07))
```
#### Expected behavior:

[What you expected to happen]
Saving The Count To The Table 
#### Actual behavior:

[What actually happened]
Sql Error Rised.

**Comment by zymawy** [comment]
Actually, This Is Happing On API Side. If Want To Add Count From API Request!

**Comment by cyrildewit** [comment]
Have you tried changing the column type of `visitor` from `string` to `text`?

https://github.com/cyrildewit/eloquent-viewable/blob/2.x/UPGRADING.md#upgrading-from-242-to-243

**Comment by zymawy** [comment]
```Shell
php artisan make:migration change_visitor_column_on_views_table --table=views
```
On `ChangeVisitorColumnOnViewsTable`
```php
        Schema::table('views', function (Blueprint $table) {
            $table->text('visitor')->change();
        });
```
