### ISSUE TITLE
addView() not stored in database

### ISSUE THREAD

**Issue by TechShankar** [cyrildewit/eloquent-viewable#127]
- Eloquent Viewable: 2.5
- Laravel Version: 5.6
- PHP Version: 7.1.20
- Database Driver & Version: innodb 

### Description:

all setup corrcectly but view count not store in database please help

**Comment by cyrildewit** [comment]
Please add the version numbers and provide me some more information. Are there any error messages? Anything in the log? Where do you call the addView method? Are you calling the adView method on a filled model?

**Comment by TechShankar** [comment]
updated comment. i call addview method in controller show method after model find.

**Comment by cyrildewit** [comment]
If you output the model using `dd()`, do you see a filled model instance?
