### ISSUE TITLE
Suggestions for v4.0.0

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/eloquent-viewable#131]
I'm trying to make up a list of features/improvements the major version should contain.

Please share your idea and vote using the 👍 and 👎. 

Thanks!

## Accepted

- ~Replace the `string $direction = 'desc'` argument of the order by views query scopes with `bool $descending = true`.~
- ~Refactor the `ViewSessionHistory` class~
- ~Rename methods with prefix `overide*()` methods to `use*()` (no bc)~

## Potential

- Archive views after a specified time
- Ability to use a simple counter over storing all the page views
- Ability to disable the visitor cookie for privacy reasons

**Comment by mauriziocalarese** [comment]
Choose if track "not unique" views.

**Comment by cyrildewit** [comment]
@mauriziocalarese I already had something in my mind for this a few months ago, but at that stage it wasn't really smart to implement it due to the package API. My idea was to use a varient of "strategy" pattern to give developers a choice to use a desired strategy that fits his needs. I don't know if it suitable, so I will need to do a few experiments.

Where were you thinking about? We can't just toggle the unique view tracking off, because this package basically stores every view.

**Comment by mauriziocalarese** [comment]
I was thinking something like to use a different method to choose if track unique views, for example:

views($post)->recordOnlyUnique();

The method checks if is already stored a view for that model with that Ip.
If present, not stores, otherwise saves that view.

**Comment by cyrildewit** [comment]
@mauriziocalarese if this solution would be okay for you, you can add this functionality using a macro (https://github.com/cyrildewit/eloquent-viewable#adding-macros-to-the-views-class)

I would love to see the end result of the macro. I may take it into account when making the final decision.

**Comment by mauriziocalarese** [comment]
I my  AppServiceProvider:

`<?php

namespace App\Providers;

use CyrildeWit\EloquentViewable\Views;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Views::macro('countAndCache', function () {
            return $this->cache()->count();
        });
    }`

In my ItemController@show:

`    public function show($id)
    {
        $item = $this->itemService->getOneWith($id, ['user', 'photos']);

        //views($item)->overrideVisitor(request()->ip())->record();

        views($item)->countAndCache();

        $item->views = views($item)->unique();

        return response()->json(new ItemResource($item));
    }`

What i get:

[2019-04-15 13:16:16] local.ERROR: Method CyrildeWit\EloquentViewable\Views::cache does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method CyrildeWit\\EloquentViewable\\Views::cache does not exist. at C:\\laragon\\www\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\Macroable.php:100)

**Comment by cyrildewit** [comment]
Sorry, my bad. It's `->remember()` not `->cache()`. Forgot to update the example.

**Comment by mauriziocalarese** [comment]
AppServiceProvider:

```
<?php
namespace App\Providers;

use CyrildeWit\EloquentViewable\Views;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Views::macro('countAndCache', function () {
            return $this->remember()->count();
        });
    }
```

ItemController@show

```
public function show($id)
    {
        $item = $this->itemService->getOneWith($id, ['user', 'photos']);

        views($item)->overrideVisitor(request()->ip())->record();
        $item->views = views($item)->countAndCache();

        return response()->json(new ItemResource($item));
    }
```

In this way it tracks the view in the db, but 0 is returned.

Can you make a working example, please?

**Comment by cyrildewit** [comment]
Isn't that `0`  returned because you're caching the views count?
