### ISSUE TITLE
General Question: What is "visitor" column value in views table composed of?

### ISSUE THREAD

**Issue by nnvvii** [cyrildewit/eloquent-viewable#134]
Kindly let me know what the "visitor" value in the database?
Is it the session id?

**Comment by cyrildewit** [comment]
This package stores a unique key on the visitor's computer using a cookie. This cookie isn't the same as the session id.

https://github.com/cyrildewit/eloquent-viewable/blob/3.x/src/Views.php#L203
https://github.com/cyrildewit/eloquent-viewable/blob/3.x/src/VisitorCookieRepository.php

**Comment by nnvvii** [comment]
Offtopic: How about adding indexes on database columns to make queries faster? I see none of the columns in "views" table are indexed.

**Comment by nnvvii** [comment]
@cyrildewit 
Offtopic: How about adding indexes on database columns to make queries faster? I see none of the columns in "views" table are indexed.

**Comment by cyrildewit** [comment]
@nnvvii Whoops. Didn't see your last comment. Can you give me an example on how this would look like in the migration?

I saw an issue a few days ago in the laravel-tags package by @spatie with the same topic. It looks like they don't see it as an important default.

Feel free to send a pull request with maybe a simple benchmark.
