### ISSUE TITLE
orderByViews - Cached?

### ISSUE THREAD

**Issue by ScottyRobinson** [cyrildewit/eloquent-viewable#136]
Just a quick question, is the `orderByViews` cached? We currently have it setup so that Viewable is cached for 15 minutes but when we get 1000 people hit the site at once, the database crashes because it's doing the following SQL query:

```sql
select `posts`.*, (select count(*) from `viewsCounter` where `posts`.`id` = `viewsCounter`.`viewable_id` and `viewsCounter`.`viewable_type` = 'App\Post') as `views_count` from `posts` order by `views_count` desc limit 2
```

The `viewsCounter` table has roughly 7.4 million rows.

**Comment by cyrildewit** [comment]
No, only the `count` and `countByType` methods will be cached when calling the `remember` method.

**Comment by cyrildewit** [comment]
It's also not very hard to cache it I think. Something like this would do the job:

```php
use App\Post;

Cache::remember('ordered-posts, 60 function () {
    return Post::orderByViews();
});
```
