### ISSUE TITLE
Call to a member function lte() on integer

### ISSUE THREAD

**Issue by maitrungduc1410** [cyrildewit/eloquent-viewable#139]
Hi everyone,
I'm facing a problem. When I use `views($post)->record();`, everything is fine. But when use `delayInSession`, it prints out `Call to a member function lte() on integer`.

Is there anybody faced this issue before?

Thank you for your help!

**Comment by cyrildewit** [comment]
Yep, this is indeed a bug. Thank you for reporting. I pushed a fix to the `improvements` branch. I will soon release a new version.
