### ISSUE TITLE
Doesn't count unique views in an API.

### ISSUE THREAD

**Issue by mauriziocalarese** [cyrildewit/eloquent-viewable#141]
- Eloquent Viewable: 3.0
- Laravel Version: 5.7.21
- PHP Version: 7.1.7
- Database Driver & Version:

### Description:
I followed the instructions to install and configure the package.
I use it in an api.

### Steps To Reproduce:

In ItemController, show method, i track the view and return them at the end

```php
views($item)->record();
$item->views = views($item)->unique()->count();

return response()->json(new ItemResource($item));
```

#### Expected behavior:
I expect to count a unique visit as a view, even if i refresh.

#### Actual behavior:
Every time that i refresh the api's page, the counter increase.

**Comment by mauriziocalarese** [comment]
Also tried:

`        views($item)
            ->overrideIpAddress(request()->ip())
            ->record();

$item->views = views($item)->unique()->count();`

Without success.

**Comment by cyrildewit** [comment]
Thank you for filling in all the fields. Strange. When I created it, it worked. I will take a look at it. For now:

> every visit is stored

This is normal behaviour

> and counted

This not

**Comment by cyrildewit** [comment]
Hey @mauriziocalarese,

I released a new version with a fix. First you need to pull in the latest version of Eloquent Viewable.

After updating, you're able to use the new `overrideVisitor` method on the `Views` class, like so:

```php
// Override visitor ID (this would be supplied by your client)
views($post)
    ->overrideVisitor('Your unique visitor ID')
    ->record();
```

**Comment by mauriziocalarese** [comment]
Thank you @cyrildewit .
Passing the ip as ID with this new method, now it works 👍 

`        views($item)
            ->overrideVisitor(request()->ip())
            ->record();`

Again, thanks!
