### ISSUE TITLE
On submission of the form it give me this error... i don't know what to do am new on laravel

### ISSUE THREAD

**Issue by sebastien15** [cyrildewit/eloquent-viewable#147]
- Eloquent Viewable: #.#.#
- Laravel Version: 5.7
- PHP Version: 7.22
- Database Driver & Version:

ERROR
Argument 1 passed to CyrildeWit\EloquentViewable\Views::forViewable() must be an instance of CyrildeWit\EloquentViewable\Contracts\Viewable or null, instance of App\Post given, called in C:\wamp64\www\bahoneza\vendor\cyrildewit\eloquent-viewable\src\helpers.php on line 8

C:\wamp64\www\bahoneza\vendor\cyrildewit\eloquent-viewable\src\Views.php
        return $viewsCount;
    }
 
    /**
     * Destroy all views of the viewable model.
     *
     * @return void
     */
    public function destroy()
    {
        $this->viewable->views()->delete();
    }
 
    /**
     * Set the viewable model.
     *
     * @param  \CyrildeWit\EloquentViewable\Contracts\Viewable|null
     * @return self
     */
    public function forViewable(ViewableContract $viewable = null): self
    {
        $this->viewable = $viewable;
 
        return $this;
    }
 
    /**
     * Set the delay in the session.
     *
     * @param  \DateTime|int  $delay
     * @return self
     */
    public function delayInSession($delay): self
    {
![Uploading Capture.JPG…]()

THIS IS MY STORE METHOD IN CONTROLLER
public function store(Request $request)
    {
        $fimage = $request->file('fimage');
        $filename = time().'.'.$fimage->getClientOriginalExtension();
        $location = public_path('/fimage'.$filename);
        request()->fimage->move(public_path('/fimage'), $filename);

        $body = $request->body;

        $dom = new \DomDocument();
        @$dom->loadHtml($body, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
        $images = $dom->getElementsByTagName('img');
        foreach ($images as $k => $img) {
            $data = $img->getAttribute('src');
            list($type, $data) = explode(';', $data);
            list(, $data)      =explode(',', $data);
            $data = base64_decode($data);
            $image_name= "/upload/" . time().$k.'.png';
            $path = public_path(). $image_name;
            file_put_contents($path, $data);
            $img->removeAttribute('src');
            $img->setAttribute('src', $image_name);
        }

        $body = $dom->saveHTML(); 

        $post = new Post;

        $post->title = $request->title;
        $post->author_id = $request->author_id;
        $post->review_id = $request->review_id;
        $post->category_id = $request->category_id;
        $post->summary = $request->summary;
        $post->body = $body;
        $post->fimage = $filename;

        $post->save();

        return redirect()->route('Post.show',$post->id)->with('success', 'Post saved successfully');
    }

**Comment by reliq** [comment]
@sebastien15 ensure your `Post` model implements `\CyrildeWit\EloquentViewable\Contracts\ViewableViewable`

See: https://github.com/cyrildewit/eloquent-viewable#preparing-your-model
