### ISSUE TITLE
Call to a member function getKey() on null

### ISSUE THREAD

**Issue by robertnicjoo** [cyrildewit/eloquent-viewable#148]
- Eloquent Viewable: "^3.1"
- Laravel Version: "5.7.*"
- PHP Version: "7.2.7"
- Database Driver & Version: MySQL "5.7.19"

### Description:
I get `Call to a member function getKey() on null` when I try to open popup video in my viewable model.

#### Expected behavior:
Not to show error :)

#### Actual behavior:

Showing error above.

---

So I made my product model viewable and it works just fine, the problem accrues when I try to open popup in my product page which is loading YouTube video.

![87](https://user-images.githubusercontent.com/8672823/52986455-4147b500-342a-11e9-8b81-dff7baf0ee79.png)

Any suggestion?

**Comment by cyrildewit** [comment]
Can you check if your viewable model is not an empty instance? Before you pass it on to the `views()` helper.

**Comment by robertnicjoo** [comment]
No it's not empty, i am visiting my product and this video pop up is part of my product details. Is slider item.

**Comment by cyrildewit** [comment]
Can you try to isolate the problem and if possible provide me some code so I can reproduce it?

**Comment by robertnicjoo** [comment]
@cyrildewit 

`Controller`

```php
public function single($slug)
    {
        $product = Product::where('slug', $slug)->where('status', '=', 'active')->first();
        views($product)->record();

        //some other codes...

        return view('front.products.default', compact('product'));
    }
```

`Blade` (commented)

```html
{{$product->title}}
{!!$product->short_description!!}


//issue part
<div class="tt-product-vertical-layout">
	<div class="tt-product-single-img">
		<div>
			<button class="tt-btn-zomm tt-top-right"><i class="icon-f-86"></i></button>
			@foreach($product->photos as $photo)
			@if($loop->first)
			<img class="zoom-product" src="{{url('images')}}/{{$photo->name}}" data-zoom-image="https://www.youtube.com/embed/{{$product->video_url}}" alt="{{$product->title}}">
			@endif
			@endforeach
		</div>
	</div>
	<div class="tt-product-single-carousel-vertical">
		<ul id="smallGallery" class="tt-slick-button-vertical  slick-animated-show-js">
			@foreach($product->photos as $photo)
			@if($loop->first)
			<li><a class="zoomGalleryActive" href="#" data-image="{{url('images')}}/{{$photo->name}}" data-zoom-image="{{url('images')}}/{{$photo->name}}"><img src="{{url('images')}}/{{$photo->name}}" alt=""></a></li>
			@else
			<li><a href="#" data-image="{{url('images')}}/{{$photo->name}}" data-zoom-image="{{url('images')}}/{{$photo->name}}"><img src="{{url('images')}}/{{$photo->name}}" alt=""></a></li>
			@endif
			@endforeach



// images above show just fine even in popups but this video below when I click to open in popup show error I mentioned in my question
			@if(!empty($product->video_url))
			<li>
				<div class="video-link-product" data-toggle="modal" data-type="youtube" data-target="#modalVideoProduct" data-value="{{$product->video_url}}">
					<img src="https://www.youtube.com/embed/{{$product->video_url}}" alt="">
					<div>
						<i class="icon-f-32"></i>
					</div>
				</div>
			</li>
			@endif
		</ul>
	</div>
</div>
```

**Comment by robertnicjoo** [comment]
hello??

**Comment by cyrildewit** [comment]
Sorry, I just can't find a way to reproduce it. If it's still an issue, please create a public repository with a _fresh_ Laravel installation where you also get this error, so I can take a better look at it.

**Comment by Xoshbin** [comment]
I'm having the same error, did you find what is the issue and how to solve it please?

**Comment by cyrildewit** [comment]
Hi @Xoshbin,

If you can isolate the problem in a fresh Laravel installation and put it online in a GitHub repository, I'm happy to take a look at it. Otherwise I don't think I'm able to help you.

**Comment by Xoshbin** [comment]
Hi @cyrildewit 
It happens when it can't find the model. In my scenario when the product is not available:
```
$product = Product::where('slug', $slug)->first();
        try {
            views($product)->record();
        } catch (Exception $e) {
            abort(404);
        }
```

But the issue is, the error is not catchable so in my above code it's still giving the error.
Thanks
