### ISSUE TITLE
Problem with delayInSession

### ISSUE THREAD

**Issue by nguyenledly** [cyrildewit/eloquent-viewable#152]
Why i cannot use delayInSession()?
After i reload the page, in 1-2 seconds, it still records the new view.
![image](https://user-images.githubusercontent.com/35844864/54862888-bf71e100-4d73-11e9-8ef7-864d6abb68d5.png)
![image](https://user-images.githubusercontent.com/35844864/54862902-f2b47000-4d73-11e9-857e-932a4839990b.png)

**Comment by basilbarnaby** [comment]
Yea I have the same issue. Any resolution or ways to get this to work?

**Comment by nguyenledly** [comment]
@basilbarnaby  i don't understand clearly, but the above example that i tested in localhost. When I move it to public, delayInSession() has been solved :D. I set 3 mins for delay, and it worked.

**Comment by vc-ash** [comment]
I'm having the same issue. I'm using version 3.2
When I use: views($item)->delayInSession(10)->record();
The views record is created every time I reload the page or view the item. I also tried passing the delay as a DateTime instance in the same manner you did in the views class in the delayInSession method: $delay = Carbon::now()->addMinutes(10);
passing that value to it still doesn't do it. The view is incremented every time.

Am I missing something?

**Comment by cyrildewit** [comment]
Check if the session is the same one each time a view is being stored. It may has something to do with this.
