### ISSUE TITLE
Functionality: orderByViews using collection

### ISSUE THREAD

**Issue by Nuranto** [cyrildewit/eloquent-viewable#154]
Actual :
```orderByViews(Builder $query, string $direction = 'desc', $period = null)```

Would be great to have : 
```orderByViews(Builder $query, string $direction = 'desc', $period = null, $collection = '')```

(and same for orderByUniqueViews of course)

Usage : 
```
Post::orderByViews('asc', null, 'customCollection');
Post::orderByUniqueViews('asc', null, 'customCollection');
````

**Comment by cyrildewit** [comment]
I will add this feature after I have solved #144
