### ISSUE TITLE
N+1 Problem on foreach

### ISSUE THREAD

**Issue by BulgarianHealer** [cyrildewit/eloquent-viewable#157]
- Eloquent Viewable: 3.2.0
- Laravel Version: 5.8.16
- PHP Version: 7.3.5
- Database Driver & Version: MySQL 5.7

### Steps To Reproduce:

Example:
```php
Post::with(['author','views'])->latest()->paginate(10);

@foreach($posts as $post)
{{views($post)->unique()->count()}}
@endforeach
```

#### Expected behavior:
Expected to create one query

```php
select count(distinct `visitor`) as aggregate from `views` where `views`.`viewable_id` in (1,2) and `views`.`viewable_id` is not null and `views`.`viewable_type` = 'App\Models\Blog\Post' and `collection` is null
```
#### Actual behavior:
Creating n+1 problem, when with('views') is added is creating new query.

new query:
```php
select * from `views` where `views`.`viewable_id` in (1, 2) and `views`.`viewable_type` = 'App\Models\Blog\Post'
```

others queries:
```php
select count(distinct `visitor`) as aggregate from `views` where `views`.`viewable_id` = 1 and `views`.`viewable_id` is not null and `views`.`viewable_type` = 'App\Models\Blog\Post' and `collection` is null
```
```php
select count(distinct `visitor`) as aggregate from `views` where `views`.`viewable_id` = 2 and `views`.`viewable_id` is not null and `views`.`viewable_type` = 'App\Models\Blog\Post' and `collection` is null
```

**Comment by cyrildewit** [comment]
I'm aware of this 'issue'. That's why I added the smart caching feature as a workaround.

I can't really find a proper solution to this. How do we know if the function is used within a loop?

We could possibly do something on the side of the query builder. Like adding our own `withViews()` query scope.

**Comment by Livijn** [comment]
Maybe allow for an array/collection: `views([$postOne, $postTwo])->unique()->count()` which could output `[4, 12, 210]`.

**Comment by cyrildewit** [comment]
@BulgarianHealer now that I'm thinking about it.

To solve this issue, you need to use the `withCount` method.

Solution:

```php
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;

$posts = Post::with(['author'])->withCount('views as views_count', function (Builder $query) {
    $query->select(DB::raw('count(DISTINCT visitor)'));
})->latest()->paginate(10);
```

Then in your view:

```blade
@foreach($posts as $post)
{{ $post->views_count }}
@endforeach
```
