### ISSUE TITLE
Major performance issue

### ISSUE THREAD

**Issue by armagedan** [cyrildewit/eloquent-viewable#176]
Hi Again,

I just noticed that the `orderByUniqueViewsCount()` has a huge impact on performance. I am on cloudways, and I have tested on Digital Ocean. My vps has 1GB of RAM and 1 Core CPU. While 1 Core should normally be enough to handle my website, it takes about 10-20 seconds to load one page on my website. So I went on ahead and htop-ed the server and mysql takes 100% CPU usage. I had a simple sample page which had only pagination and about 1000 posts. The only addition to that page was the `orderByUniqueViewsCount()`. I removed it an voila. it took 0.5 seconds to load. I haven't had enough time to throurghly check what was going under the hood but I just wanted to let you know. I have a total of 1000 posts on my db and using `orderByUniqueViewsCount()` takes a very long time to load. 

Hope that was enough info.

**Comment by cyrildewit** [comment]
I don't think we can gain a faster query without storing the views count in the posts table. Right know it has to do the following steps:
1. Fetch all posts
2. Count views for each post
3. Order by views count

If your database has a lot of views, this will definitely be slow.

There are multiple strategies to fix this problem:
1. Cache complete query for a limited amount of time? Will cause mismatches with the views count (both new and cached)
2. Add a new field to posts table that contains the total unique views count, which can be updated by a cron job every hour

**Comment by armagedan** [comment]
> 2\. Add a new field to posts table that contains the total unique views count, which can be updated by a cron job every hour

This sounds like a better solution. I can’t think of a better way to be honest. At least mot right now. I’ll post it here after doing some testings
