### ISSUE TITLE
Support for Laravel 6.0

### ISSUE THREAD

**Issue by ErriourRU** [cyrildewit/eloquent-viewable#182]
Update packet for Laravel 6.0 please :)
Packet requires modules of laravel up to 5.8, so installing on 6.0 doesn't be work.

**Comment by cyrildewit** [comment]
I released `v4.1.0` https://github.com/cyrildewit/eloquent-viewable/releases/tag/v4.1.0 with support for Laravel 6.

**Comment by MarcoCazzaro** [comment]
Laravel on version 6.0 changed versioning system, now it's already at version 6.2, which cyrildewit/eloquent-viewable package is not supporting it yet, causing the upgrade to fail. Can you please have a look? To reproduce, just try to upgrade Laravel to 6.2.* .
