### ISSUE TITLE
Syntax error or access violation: 1055 

### ISSUE THREAD

**Issue by doubleprincez** [cyrildewit/eloquent-viewable#187]
- Eloquent Viewable: News
- Laravel Version: 7.2
- PHP Version: 7.3.7
- Database Driver & Version: 4.9.0.1

### Description:
News Model
```
use Conner\Likeable\LikeableTrait;
use CyrildeWit\EloquentViewable\Viewable;
use CyrildeWit\EloquentViewable\Contracts\Viewable as ViewableContract;
use Illuminate\Database\Eloquent\Model;

class News extends Model implements ViewableContract
{

    use Viewable, LikeableTrait;
}
```

News Controller
   ```
   public function index()
    {
          
        $news = News::orderByViews()->get();
    }
```

### Steps To Reproduce:

1. I created a new project having the following requirements

        "cyrildewit/eloquent-viewable": "^4.1",
        "fideloper/proxy": "^4.0",
        "intervention/image": "^2.5",
        "jorenvanhocht/laravel-share": "^3.1",
        "laravel/framework": "^6.2",
        "laravel/telescope": "^2.1",
        "laravel/tinker": "^1.0",
        "laravel/ui": "^1.1",
        "laravelcollective/html": "^6.0",
        "rtconner/laravel-likeable": "~1.2",
        "spatie/laravel-google-calendar": "^2.3",
        "tcg/voyager": "^1.3",
        "watson/active": "^4.0"

#### Expected behavior:
Needed to pick the most viewed news from the collection

#### Actual behavior:
It kept on throwing this error:
 ```
 SQLSTATE[42000]: Syntax error or access violation: 1055 'laravel_hrm_db.news.title' isn't in GROUP BY (SQL: select news.*, count(visitor) as views_count from `news` left join `views` on `views`.`viewable_id` = `news`.`id` and `views`.`viewable_type` = App\News group by `news`.`id` order by `views_count` desc)
 ```

[What actually happened]
Im getting this error every time I tried to fetch news ordering by views
$news = News::orderByViews()->get();

**Comment by Agusfn** [comment]
Just had this problem. Solved it with
https://stackoverflow.com/questions/40917189/laravel-syntax-error-or-access-violation-1055-error
