### ISSUE TITLE
Problem with orderByViews & orderByUniqueViews

### ISSUE THREAD

**Issue by piep14** [cyrildewit/eloquent-viewable#188]
- Eloquent Viewable: 
- Laravel Version: 6.6
- PHP Version: 7.3
- Database Driver & Version: mariadb

### Description:

I think there is a problem with the orderByViews and Period method because it sends me the same thing as orderByUniqueViews

I have 3 lines in my table, 2 of them on the same model.

The 2 methods return me 2 lines.

`$property_views = Property::orderByUniqueViews('asc', Period::since('2019-12-02'))->get();`

`$property_views = Property::orderByViews('asc', Period::since('2019-12-02'))->get();`

**Comment by piep14** [comment]
@cyrildewit  an idea ? Tks

**Comment by cyrildewit** [comment]
Are you trying to get the views count (`$property_views`)? Or are you trying to get a collection of Property entities ordered by views / unique views?

To get the views count you need to use:

```php
$property_views = views($propertyModelInstance)->period(Period::since('2019-12-02'))->count()
$property_views = views($propertyModelInstance)->period(Period::since('2019-12-02'))->unique()->count()
```

To get an collection of Property models orderd by views / unique views count:

```php
$properties = Property::orderViews('asc', Period::since('2019-12-02'))->get();
$properties = Property::orderByUniqueViews('asc', Period::since('2019-12-02'))->get();
```

Can you show me what you want to achieve and what you get?

**Comment by piep14** [comment]
@cyrildewit 

I try : 

`$property_views = views(Property::class)->period(Period::since('2019-12-02'))->count();`

OR

`$property_views = views('App\Model\Property')->period(Period::since('2019-12-02'))->count();`

> Argument 1 passed to CyrildeWit\EloquentViewable\Views::forViewable() must implement interface CyrildeWit\EloquentViewable\Contracts\Viewable or be null, string given

But, working : 

`$property_views = Property::orderByUniqueViews('asc', Period::since('2019-12-02'))->get()->sum('views_count');`

**Comment by cyrildewit** [comment]
Hi @piep14,

Little bit late, but it seems that you forgot to add the ViewableContract to your Property model definition. See the error message.

https://github.com/cyrildewit/eloquent-viewable/blob/master/README.md#preparing-your-model
