### ISSUE TITLE
[Question] Check if views exist

### ISSUE THREAD

**Issue by Teranode** [cyrildewit/eloquent-viewable#190]
How would you check to see if views exist on a model instance?
Would you do:
```
$post->views()->exist();
```
or 
```
views($post)->exist();
```

**Comment by cyrildewit** [comment]
The only way to do it is by using `$post->views()`. This is an Elqouent relationship (one to many) where the `exists()` method on exists.

The `views($post)` helper returns an instance of `CyrildeWit\EloquentViewable\Views` which doesn't contain this method.

**Comment by Teranode** [comment]
Alright thank you.
