### ISSUE TITLE
500 error while testing

### ISSUE THREAD

**Issue by damianmadronal** [cyrildewit/eloquent-viewable#191]
- Eloquent Viewable: ^4.0.
- Laravel Version: 6.9.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 5.7.26

### Description:
I'm making a test function for deleting items in my database. when i run the test i get a 500 error with this in my error log: 

testing.ERROR: Argument 1 passed to CyrildeWit\EloquentViewable\ViewableObserver::deleted() must implement interface CyrildeWit\EloquentViewable\Contracts\Viewable, instance of App\Model\Company given {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0)

### Steps To Reproduce:
This is the piece of code that deletes the item in my database: 

$response = $this->actingAs(self::getUser(1))->delete("adm/bedrijvengids/$id");

$company = Company::withTrashed()->findOrFail($id);

$this->assertTrue($company->trashed());

$response->assertRedirect();

#### Expected behavior:
response 302

#### Actual behavior:
response 500

**Comment by cyrildewit** [comment]
Hey @damianmadronal,

Have you read the error message? It says that your `App\Model\Company` model must implement the `CyrildeWit\EloquentViewable\Contracts\Viewable` interface.

Docs: https://github.com/cyrildewit/eloquent-viewable#preparing-your-model
