### ISSUE TITLE
Config to limit incrementing views for a given IP over a defined period

### ISSUE THREAD

**Issue by cioraneanu** [cyrildewit/eloquent-viewable#192]
I think a really helpful feature would be define a value in eloquent-viewable like
`'remember_ip' => 15 * 60, // seconds`
so that we can avoid incremental view spam from an user.

**Comment by cyrildewit** [comment]
Hey,

This is already possible. I've called it session delays.

See https://github.com/cyrildewit/eloquent-viewable/blob/master/README.md#recording-views-with-session-delays

Please let me know if this is what you were looking for.
