### ISSUE TITLE
Laravel 7.0 Support

### ISSUE THREAD

**Issue by kfirba** [cyrildewit/eloquent-viewable#202]
Hey!

This is a friendly reminder that Laravel 7.0 is officially out!  🥳
Can you tag a new release that supports 7.0 (I believe the only change that's needed is changing the composer.json file)?

Thanks!

**Comment by kfirba** [comment]
My bad. I assumed it was out since I saw the new documentation tab. Anyways, it should be out any day now :)

**Comment by cyrildewit** [comment]
Hi,

Support for Laravel 7 is planned for `v5.0.0`. I am trying to release it as fast as possible.

I'm open for a pull request with Laravel 7 support for v4, only if it doesn't require any breaking changes and contains a GitHub actions workflow that runs the test suite like in the `release/5.0.0` branche.

Thanks for the heads up!

**Comment by francoism90** [comment]
@cyrildewit Thanks. :)

**Comment by kfirba** [comment]
@cyrildewit when does V5 is coming out?

**Comment by francoism90** [comment]
@kfirba 
https://github.com/cyrildewit/eloquent-viewable/issues/206#issuecomment-596103255

Remember this is an alpha version and @cyrildewit already mentioned things may change. I'm currently testing this with Laravel 7 and didn't found any issues, just things I needed to refactor. However your experience may differ.

**Comment by cyrildewit** [comment]
@kfirba I hope this weekend but depends on the feedback. Closing this issue for now.
