### ISSUE TITLE
Unique count not working

### ISSUE THREAD

**Issue by poojakbs** [cyrildewit/eloquent-viewable#204]
- Eloquent Viewable: "^3.2",
- Laravel Version:"5.8.*"
- PHP Version:"^7.1.3"

views($post)->unique()->count()
Instead of  total unique count of post getting  count in response.

**Comment by cyrildewit** [comment]
Hi,

Can you upgrade to `^4.0` and check if this issue is still persistent? I can remember that I solved a similar bug in v4.

If it's not fixed, can you provide a testcase?

Thanks!

**Comment by dabbit** [comment]
Yes, it seems like not working for me too!

Here is my snippet.

```php
$question = Question::where('id', $id)->firstOrFail();
views($question)->unique()->count();
```

1. I tried logging out
2. Cleared all the cookies
3. Login as another user
4. Viewed the same page

but the views are not incremented.

### Env Details

**PHP** 7.3
**Laravel** 7.22.4
**Eloquent Viewable** 5.2

cc @cyrildewit

**Comment by cyrildewit** [comment]
Hi @dabbit,

Is the snippet you provided the only code you have inside your controller?

If so, you're actually not recording new views.

This code, `views($question)->unique()->count();`, will **count** all the unique views in your database.

To **record** a view, you will have to call the `record()` method: `views($question)->record();`.

Your controller action should look similar to this:

```php
public function show($id)
{
    $question = Question::where('id', $id)->firstOrFail();

    views($question)->record();

    return view('question.show', compact('question'));
}
```

Let me know if this fixes your issue.

**Comment by dabbit** [comment]
Woah thanks @cyrildewit! I haven't noticed yet 🤣
