### ISSUE TITLE
[5.x] Tags support and release date

### ISSUE THREAD

**Issue by zefexdeveloper** [cyrildewit/eloquent-viewable#206]
I was wondering, is it possible to add tag support? For example, I'm creating a website where I will be using to track unique visitors (for a page) but also for unique views (someone saw the ad).
To make it simpler to understand, imagine that you enter on a classifieds website and you see a lot of ads, it will count as a view for them but won't count as a visit, once the user clicks on an ad to see it will count the visit and for that I need tags so I can retrieve the views by tag. What you can do is use a default tag like 'views' and whenever the user `views($post)->count()` it will return the tag `views` but allowing the specification of the tag like `views($post, 'visits')->count()`.

The other question I have is: do you have a release date in mind for v5? I will be deploying the website in around 15 days and I really wanted to change the view package to this one, the other has a really bad performance.

**Comment by francoism90** [comment]
You can use collections and even add multiple view trackers:
```
views($post)->collection('tag1')->record();
views($post)->collection('tag2')->record();
```

**Comment by cyrildewit** [comment]
Hi @zefexdeveloper,

As already mentioned by @francoism90, you can use the [collection method](https://github.com/cyrildewit/eloquent-viewable#view-collections). 

> Do you have a release date in mind for v5?

No, I try to finish it as fast as possible, but I still have a lot of ideas to try and implement. I have also made quite a few big changes that I want to test myself, to make sure I don't miss anything. If you really can't wait, I may release an alpha version, but I can't guarantee a stable upgrade path when releasing the actual v5.

**Comment by reliq** [comment]
@cyrildewit +1 for alpha version

**Comment by cyrildewit** [comment]
I just released [`v5.0.0-alpha.0`](https://github.com/cyrildewit/eloquent-viewable/releases/tag/v5.0.0-alpha.0). I'm happy to receive your feedback.

**Comment by francoism90** [comment]
@cyrildewit Thanks for releasing an alpha version! Should we open another issue for feedback or keep using this topic?

**Comment by cyrildewit** [comment]
You can provide your feedback in issue #170. Thanks.

**Comment by zefexdeveloper** [comment]
Thank you @cyrildewit. Is there too many breaking changes from 4 to 5? I need to use it in production and I would like to upgrade to 5 in the future but I'm afraid if there's too many breaking changes it won't be possible.

**Comment by francoism90** [comment]
@zefexdeveloper I cannot speak for @cyrildewit, just from a tester POV: things I needed to refactor were some queries, update the views table (id > to bigint) and the config was changed. If you need to use it in production, it may be better to wait for the release of V5.

**Comment by cyrildewit** [comment]
@zefexdeveloper 

> Are there too many breaking changes from 4 to 5? 

It depends on what features you're using. The main features like:

* `views($post)`
* `->period()`
* `->unique()`
* `->record()`
* `->count()`

Remains the same in terms of API. The underlying query has changed, but I don't think it will break in most use cases.

One important change to note is that I renamed the `delayInSession` method to `cooldown`.

If you have extended the package in some ways, things will probably break. The best way to tell is to view the comparison.

**Comment by zefexdeveloper** [comment]
@francoism90 @cyrildewit Yes, I think that changes in the API is okay as it's in the code and you can change easier, the problem is when something is changing on the database, like the table, renaming or changing some fields type and things like that while you have already something in production.
The problem tho is that I need to put this thing online in around 15~20 days, I hope it's released until there (it would save me cause the one I'm using is REALLLLLLLY bad, it has a shitty performance)

**Comment by cyrildewit** [comment]
I don't think that I'm going to make breaking changes in the database schema. The database design is in my opinion finished. And if I would change something, it will be possible to migrate. 

May I ask you which package you are currently using? Or are you talking about v4.

**Comment by francoism90** [comment]
The scheme as been updated in V5 (id to bigint), maybe this should be added into the upgrade guide.

**Comment by zefexdeveloper** [comment]
@cyrildewit I'm currently using https://github.com/awssat/laravel-visits, for some reason it does A LOT of queries to the database.
As I'm creating a classified website I need to increase the views of each ad when they are listed and the user see it, also when the user visit an ad. I'm currently listing 20 ads per page, I added tried to count the view for each one and it ended up doing 700 queries to the database... 700!
I will keep using it until the release date that is around 15/20 days, if you publish it I will migrate before deploying the application, if not, I will see what to do by then :joy:

And by the way, your commitment to the package is amazing, since the beginning you are here, that is something really important and I really appreciate that.

Keep up the good work.

@francoism90 Yes, perhaps it should, would help people upgrade without problems.

**Comment by cyrildewit** [comment]
@zefexdeveloper thank you for the kind words! 

>  I'm currently listing 20 ads per page, I added tried to count the view for each one and it ended up doing 700 queries to the database... 700!

Woah! That's a lot...

**Comment by zefexdeveloper** [comment]
@cyrildewit Yes, it is and that is why I'm looking for an alternative, I can't handle 700 queries for a simple view counting haha.

**Comment by cyrildewit** [comment]
Since this issue is resolved, I'm going to close it for now.
