### ISSUE TITLE
another database save

### ISSUE THREAD

**Issue by sefaiyi** [cyrildewit/eloquent-viewable#208]
- Eloquent Viewable: "cyrildewit/eloquent-viewable": "^3.1",
- Laravel Version: 5.8.37
- PHP Version: 7.2.2
- Database Driver & Version: Mysql 5.7 innodb

Hi bro, 

Thanks a lot for the package first..

I want to record the record I want to make to another database I have defined.

Please help this for subject.

**Comment by cyrildewit** [comment]
Hi,

If you want to store the views in a different database, you can configure a different connection in the config file. If you can't find it, you will need to publish it using:

```bash
php artisan vendor:publish --provider="CyrildeWit\EloquentViewable\EloquentViewableServiceProvider" --tag="config"
```

**Comment by sefaiyi** [comment]
> Hi,
> 
> If you want to store the views in a different database, you can configure a different connection in the config file. If you can't find it, you will need to publish it using:

thank you very much bro.
