### ISSUE TITLE
Storing Custom information about visitor Examples

### ISSUE THREAD

**Issue by JonPurvis** [cyrildewit/eloquent-viewable#210]
Hello!

Would you be able to provide an example in the documentation of how you'd store say, the logged in user ID with a view? I'm trying to implement it in my application and I'm just hitting errors, it's 100% my code so I'm just after some clarification that's all, it may help others out too?

Thanks!

**Comment by JonPurvis** [comment]
Had another stab at this tonight.

I've created a custom `Visitor` class:
```
<?php
namespace App\Classes;

use CyrildeWit\EloquentViewable\Contracts\CrawlerDetector;
use Illuminate\Contracts\Config\Repository as ConfigRepository;
use Illuminate\Http\Request;

class Visitor extends \CyrildeWit\EloquentViewable\Visitor
{
  public function __construct(Request $request, CrawlerDetector $crawlerDetector, ConfigRepository $config)
  {
    parent::__construct($request, $crawlerDetector, $config);
  }
}
```

Then in `AppServiceProvider` I bind it:

```
$this->app->bind(
  CyrildeWit\EloquentViewable\Contracts\Visitor::class
  Visitor::class
);
```

Then in the Controller:
```
views($test)
  ->useVisitor(new Visitor())
  ->record();
```

Which gives me the following:

`Too few arguments to function App\Classes\Visitor::__construct(), 0 passed in /var/www/app/Http/Controllers/TestController.php on line 88 and exactly 3 expected`

**Comment by cyrildewit** [comment]
@JonPurvis as the exception says you need to pass the three missing arguments to the Visitor class.

To solve this, you need to resolve the Visitor class from the container using the `app()` helper or using the `Illuminate\Container\Container` class.

```php
use App\Classes\Visitor;

views($test)
  ->useVisitor(app(Visitor::class))
  ->record();
```

I'm working on an example in the [cyrildewit/eloquent-viewable-demo-app](https://github.com/cyrildewit/eloquent-viewable-demo-app) repository. I will share a link when I've finished it.

**Comment by cyrildewit** [comment]
You can do two things to link a user to view:

## Store user id in visitor column

You can extend the `Visitor` class and return the user id from the `id()` method. It's not the best option in my opinion. It would be cleaner to create a dedicated user_id column to the views table.

## Store user id in views table

If you want to store the user id in a dedicated user_id column you will have to do the following things:

1. Create migration that adds `user_id` to `views` table.
2. Extend `View` Eloquent model to add the belongs to user relationship.
3. Extend `Views` class
    * Add `protected $viewer;`
    * Add `public function viewedBy(User $user) {$this->viewer = $user; return $this;}`
    * Update the `record()` method to add the user id to the user_id column.

The you can add the viewer like:

```php
views($post)
    ->viewedBy($user)
   ->record();
```

**Comment by JonPurvis** [comment]
Thanks @cyrildewit 😄 

```
<?php

namespace App\Classes;

use App\User;
use Carbon\Carbon;
use Illuminate\Container\Container;
use CyrildeWit\EloquentViewable\Contracts\View as ViewContract;

class Views extends \CyrildeWit\EloquentViewable\Views
{
  protected $viewer;

  public function viewedBy(User $user)
  {
    $this->viewer = $user;
    return $this;
  }

  /**
   * @return ViewContract|mixed|void
   * @throws \Illuminate\Contracts\Container\BindingResolutionException
   */
  public function record()
  {
    if (!$this->shouldRecord()) {
      return;
    }

    $view = Container::getInstance()->make(ViewContract::class);
    $view->viewable_id = $this->viewable->getKey();
    $view->viewable_type = $this->viewable->getMorphClass();
    $view->visitor = $this->id;
    $view->collection = $this->collection;
    $view->viewed_at = Carbon::now();
    $view->save();

    return $view;
  }
}
```

This is my Views class. When I view the page that executes the record code, I get this:

```
Method CyrildeWit\EloquentViewable\Views::viewedBy does not exist.
```

So it looks to not be using my Class. Have I missed something really obvious? 😭 

Thanks again!

**Comment by cyrildewit** [comment]
Can you update the package to `v5.2.0` and see if it's fixed? 

About your record method, you can retrieve the visitor id from `$this->visitor->id();`. This is a unique key stored in a cookie.

**Comment by JonPurvis** [comment]
Hey @cyrildewit!

Managed to get it working, I'll paste what I did below incase you can think of a better way of doing it:

- Created `ViewsHelper` Helper file which takes the `views` method from `helpers.php`.
- Took
```
$builder = Container::getInstance()->make(Views::class);
```
and changed it to use my `Views` class
- Updated the `Views` class and swapped `$this->visitor->id()` to `$this->visitor->id`
- Updated the record part of my Controller to
```
ViewsHelper::views($test)
  ->viewedBy(Auth::user())
  ->record();
```

Now I get the User ID in the database
![image](https://user-images.githubusercontent.com/7534029/77826634-797af600-7108-11ea-8006-e90498f3f178.png)

This is the functionality I wanted so thanks for helping me get there! I'm not sure if what I've done above is the _best_ way of doing it, but it is a way!

**Comment by cyrildewit** [comment]
Hi @JonPurvis,

If you update to `v5.2.0`, you should be able to bind your custom Views instance to the `CyrildeWit\EloquentViewable\Contracts\Views` namespace. Then you can use the provided `views()` helper.

Just to be sure: are you storing the user id in the `visitor` column? Or have you created a new `user_id` column?

**Comment by JonPurvis** [comment]
Binding worked 😄 I've removed my Helper file as it's useless now.

For now I'm just storing it in the Visitor column just whilst I got it to actually store the ID somewhere. Next step will be to swap it over to use a `user_id` column.

Thanks again for all your help, really appreciate it 👍
