### ISSUE TITLE
Trait 'CyrildeWit\EloquentViewable\InteractsWithViews' not found

### ISSUE THREAD

**Issue by yudifaturohman** [cyrildewit/eloquent-viewable#213]
- Eloquent Viewable: #.#.#
- Laravel Version: 5.8.37
- PHP Version: 7.1
- Database Driver & Version:
Error Trait 'CyrildeWit\EloquentViewable\InteractsWithViews' not found

please respons

**Comment by cyrildewit** [comment]
Which version do you have installed?

**Comment by amin98362** [comment]
I have same problem, I installed cyrildewit/eloquent-viewable (v4.1.1)

**Comment by cyrildewit** [comment]
Check out the documentation for `v4.1.0` at https://github.com/cyrildewit/eloquent-viewable/tree/v4.1.1. Things have changed.

**Comment by cyrildewit** [comment]
If the error still occurs, just comment on this issue and I will reopen it.
