### ISSUE TITLE
Add support Laravel ^7.1

### ISSUE THREAD

**Issue by mishabachkur** [cyrildewit/eloquent-viewable#215]
- Eloquent Viewable: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Steps To Reproduce:

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior:

[What you expected to happen]

#### Actual behavior:

[What actually happened]

**Comment by SamAriafar** [comment]
@mishabachkur That's already supported, I'm using it on the latest version of Laravel (v7.2.6).

**Comment by cyrildewit** [comment]
@mishabachkur can you provide more details?

**Comment by mishabachkur** [comment]
![image](https://user-images.githubusercontent.com/3975266/79858700-7eb22480-83d8-11ea-990d-324a604efd7a.png)
@cyrildewit

**Comment by mishabachkur** [comment]
@SamAriafar You are right. I was using v4.1, that was the problem. 

@SamAriafar @cyrildewit Thanks for the quick reply
