### ISSUE TITLE
Migrate Command Gives Error: Incorrect Table Name

### ISSUE THREAD

**Issue by reasecret** [cyrildewit/eloquent-viewable#216]
- Eloquent Viewable: 5.2
- Laravel Version: 7.12
- PHP Version: 7.3
- Database Driver & Version: Mysql

I've tried to install package. When I run migrate command terminal give this error:
`  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` bigint unsigned not null auto_increment primary key, `viewable_type` varchar(255) not null, `viewable_id` bigint unsigned not null, `visitor` text null, `collection` varchar(255) null, `viewed_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

Table name is coming from config file. If we don't publish config file, migration does not working. Documentation says: _You can optionally publish the config file_. But it's not optional in this situation.

First config file must published. Or table name could defined in migration file manually.

**Comment by dmyers** [comment]
Also ran into this. Maybe it is a MySQL 8 issue? I tried it locally with MySQL 5.7 and it was fine.

**Comment by dmyers** [comment]
Actually maybe make sure your config cache is clear too, that was my issue.

`php artisan config:clear`

**Comment by cyrildewit** [comment]
@reasecret the default published migration uses the configured table name. Looking at the error, it seems that your config instance doesn't have a value for the `eloquent-viewable.models.view.table_name` key.

Can you tinker around and see if for example `config('eloquent-viewable.models.view.table_name')` returns something?

**Comment by cyrildewit** [comment]
Publishing the config file should be optional because we merge the default config file inside the `register` method in the service provider.

https://github.com/cyrildewit/eloquent-viewable/blob/master/src/EloquentViewableServiceProvider.php#L49

Have you already tried the suggestion from @dmyers?

**Comment by reasecret** [comment]
I've already installed package, after publishing config file. Now there is no problem with installation.

I'm just saying, if I didn't publish config, migration wouldn't work because there is no defined table name in migration file, right? I've tried 3 times (without publishing eloquent-viewable config) and got error.

And I've tried config:clear and config:cache. Nothing changed.

**Comment by MuriloEduardo** [comment]
> Na verdade, talvez tenha certeza de que seu cache de configuração está limpo também, esse era o meu problema.
> 
> `php artisan config:clear`

It works for me!

**Comment by webfuelcode** [comment]
Yes, clearing the cache helped me.

`php artisan config:clear`
