### ISSUE TITLE
Need to update the doc

### ISSUE THREAD

**Issue by bjgajjar** [cyrildewit/eloquent-viewable#219]
### Description:

The link of documentation for [`Update overrideIpAddress and overrideVisitor usages` ](https://github.com/cyrildewit/eloquent-viewable/blob/master/UPGRADING.md#update-overrideipaddress-and-overridevisitor-usages) is wrong. 

It's `https://github.com/cyrildewit/eloquent-viewable/blob/master/readme.md#custom-visitor-information` but is should `README.md`

**Comment by cyrildewit** [comment]
Hi @bjgajjar, thank you for reporting. I've updated it.
