### ISSUE TITLE
Total views count

### ISSUE THREAD

**Issue by MahbodHastam** [cyrildewit/eloquent-viewable#221]
- Eloquent Viewable: 5.2
- Laravel Version: 7.0
- PHP Version: 7.4

Hi, how can i get all total views count?!

**Comment by cyrildewit** [comment]
```php
$post = Post::find(1)

// #1 - Total views count of a Post entry
$count = views($post)->count();

// #2 - Total views count of a viewable type (Eloquent model)
$count = views(new Post())->count();
$count = views(Post::class)->count();

// #3 - Total count of all stored views
use CyrildeWit\EloquentViewable\View; // Eloquet model

$count = View::count()
```
---

* https://github.com/cyrildewit/eloquent-viewable#get-total-views-count
* https://github.com/cyrildewit/eloquent-viewable#get-views-count-of-viewable-type
* https://github.com/cyrildewit/eloquent-viewable/blob/master/src/View.php
