### ISSUE TITLE
view record error

### ISSUE THREAD

**Issue by riyan-amanda** [cyrildewit/eloquent-viewable#222]
- Eloquent Viewable: 5.2
- Laravel Version: 7.x
- PHP Version: 7.3.7
- Database Driver & Version:

### TypeError:
Argument 1 passed to CyrildeWit\EloquentViewable\Views::forViewable() must be an instance of CyrildeWit\EloquentViewable\Contracts\Viewable or null, instance of App\Models\Post given, called in C:\xampp\htdocs\lingkaran\vendor\cyrildewit\eloquent-viewable\src\helpers.php on line 20

### My Post Route

`route::prefix('post')->group(function () {
        Route::get('/{category}/{post}', 'HomeController@show')->name('post.show');
    });`

### My Post Model

`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use CyrildeWit\EloquentViewable\Contracts\Viewable;

class Post extends Model
{
    use InteractsWithViews;

    // Menambah kolom yang tidak bisa di input ke database
    protected $guarded = [
        'id'
    ];

    /**
     * All of my relations
     */

    // Deklarasi link yang tampil di url
    public function getRouteKeyName()
    {
        return 'slug';
    }
}`

### My Controller

`public function show(Category $category, Post $post)
    {
        $relatedPosts = Post::where('category_id', $category->id)->where('id', '<>', $post->id)
        ->where('status', 1)->orderByRaw('RAND()')->take(8)->get();
        $populerPosts = Post::where('status', 1)->where('view', '>=', 1)->orderBy('view', 'DESC')->take(4)->get();
        $terbaruPosts = Post::with('user_author')->where('status', 1)->latest()->take(5)->get();
        
        views($post)->record();

        return view('guest.post', compact('post', 'relatedPosts', 'populerPosts', 'terbaruPosts'));
    }`

I don't know why this error appears, can anybody help?

**Comment by cyrildewit** [comment]
Hi,

It looks like you forgot to implement the `Viewable` interface in your Post model definition.

https://github.com/cyrildewit/eloquent-viewable#preparing-your-model

Please let me know if this error still occurs.

Regards,
Cyril

**Comment by riyan-amanda** [comment]
its work, I'm sorry not thorough enough.
thanks for your help.
