### ISSUE TITLE
Save IP of the visitor.

### ISSUE THREAD

**Issue by Alejobcn** [cyrildewit/eloquent-viewable#224]
- Eloquent Viewable: 5.2
- Laravel Version: 7.16.1

### Question:

How is it possible to save the visitor's IP?

In the event that it is not available, when will it be available?

Thank you.

**Comment by cyrildewit** [comment]
Hi @Alejobcn,

I like to keep the package free from very user specific needs. Once a feature is added to the core it's not easy to opt-out. 

You can extend the package and add this functionality yourself.

Quick thought of how I would solve it:
1. Update views table to contain ìp_address`
2. Create custom View model
3. Add custom macro to Views class which fills the `ip_address` field

If you encounter any issues in the process of solving it, feel free to open another issue.

---

* https://github.com/cyrildewit/eloquent-viewable#using-your-own-view-eloquent-model
* https://github.com/cyrildewit/eloquent-viewable#adding-macros-to-the-views-class
