### ISSUE TITLE
remove views when model is forcedelete

### ISSUE THREAD

**Issue by Thehornyboy** [cyrildewit/eloquent-viewable#225]
Dear reader, 
Good day to you
Hopefully you are all ok during this difficult time.
first of all thanks for the effort you make to develop this awesome package , it really save lot of developer time like me haha
I am using it with my post model, below command is working 100%.

protected $removeViewsOnDelete = true;

but my post model is implement softdelete i would like to delete its associated view when I forcedelete the post model are there any turnaround ? thanks

**Comment by cyrildewit** [comment]
Hi @Thehornyboy,

I've tried to reproduce your issue, but it looks like it should be working fine.

I created the following test: https://github.com/cyrildewit/eloquent-viewable/compare/feature/fix-issue-225

And the PHPUnit test results: https://github.com/cyrildewit/eloquent-viewable/actions/runs/193108700

The forceDelete() method fires the `deleted()` event in the `ViewableObserver`, which removes the views.

**Comment by cyrildewit** [comment]
Hi @Thehornyboy,

I've tried to reproduce your issue, but it looks like it should be working fine.

I created the following test: https://github.com/cyrildewit/eloquent-viewable/compare/feature/fix-issue-225

And the PHPUnit test results: https://github.com/cyrildewit/eloquent-viewable/actions/runs/193108700

The forceDelete() method fires the `deleted()` event in the `ViewableObserver`, which removes the views.

**Comment by Thehornyboy** [comment]
hey @cyrildewit ,
good day to you,
protected $removeViewsOnDelete = true; 
is working , When I delete the post its view also deleted , but when I restore the post the view is gone . when I delete the post I also want to keep the view.when I forcedelete the post then delete the view. thx

**Comment by cyrildewit** [comment]
Hi @Thehornyboy,

This is not supported out of the box. You will have to extend the package to make the views table soft deletable and restore the views when the Viewable model is restored.

I would recommend to not use the built-in `$removeViewsOnDelete` property, but to make your own observable that listens to the `restored ` event of your `Viewable` model and then call the `restore` method on the views relationship.

**Comment by cyrildewit** [comment]
I gave it a try and it's pretty doable. See test `somethings3` inside `ViewableObserverTest`.

* https://github.com/cyrildewit/eloquent-viewable/compare/feature/fix-issue-225
* https://github.com/cyrildewit/eloquent-viewable/actions/runs/196401998

Let me know if you encounter any issues while solving it in your project.

**Comment by Thehornyboy** [comment]
hi bro ,  thanks for your answer 
I come up a shorter way , when I forcedelete the post I just revome the the view by calling
views($post)->destroy();
we dnt need to implement softdelete on view model , we can make it simple thanks
