### ISSUE TITLE
record() issue

### ISSUE THREAD

**Issue by gaiahub** [cyrildewit/eloquent-viewable#227]
- Eloquent Viewable: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Steps To Reproduce:

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior:

[What you expected to happen]

#### Actual behavior:

[What actually happened]

Im getting `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'viewable_id' cannot be null `

**Comment by cyrildewit** [comment]
Please use the issue template or provide at least some code so I can try to reproduce it.

**Comment by hasbi001** [comment]
Hallo Friend,
I have same issue.
i have follow the instuction for configuration and for record.
here is a snippet of the code :
Model :
<?php

namespace Custom\Classes\Models;

use Illuminate\Database\Eloquent\Model;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use CyrildeWit\EloquentViewable\Contracts\Viewable;

class ClassesViews extends Model implements Viewable {
	use InteractsWithViews;

	protected $table = 'product';
}

Controller :
public function index(Request $request) {
       $logClasses = new ClassesViews();
        views($logClasses)->record();
      return view('classes.index', compact('logProduct'));
}

thank you

**Comment by cyrildewit** [comment]
If you think about it, it makes sense. Right now, you're creating a new instance of your Viewable model. This instance isn't stored in the database and therefore doesn't contain a primary key (id). This primary key is necessary to bind a view to it.

I will look if I can show a better error message.
