### ISSUE TITLE
Return data as collection group by date.

### ISSUE THREAD

**Issue by kamekun** [cyrildewit/eloquent-viewable#231]
- Eloquent Viewable: lasted

### Description:
Sorry if this a dump question butt.. is there a way to return the values as group date, like:  days,months, years

```
{ "2020-08-1" : 34, "2020-08-2": 36, "2020-08-3:32, . . . }

or this example by months

[ "6" => ['unique' =>  34, 'views' => 60],
"7" => ['unique'  => 1, 'views' => 3],
"8" => ['unique' =>  15, 'views' => 20]  
]
```

**Comment by Alejobcn** [comment]
Hello,

I am also interested in the answer to the question.

Is this possible to do?

Thank you

**Comment by cyrildewit** [comment]
This is definitely possible. Use your problem-solving skills to tackle it. I would try to leverage most of the work to the database. You can use the `views` relation directly on your `Viewable` model to build some SQL queries.
