### ISSUE TITLE
Delete views

### ISSUE THREAD

**Issue by Marcolino92** [cyrildewit/eloquent-viewable#232]
How is it possible to cancel the visits corresponding to a deleted post? As there is no relationship between "viewable_id" and the post id.

**Comment by cyrildewit** [comment]
Do you mean deleting the views of a deleted viewable model?

If the viewable model still exists:

```php
// using views helper
views($post)->destroy();

// using direct views relationship
$post->views()->delete();
```

If the viewable model has already been deleted:

```php
use CyrildeWit\EloquentViewable\View;

View::where('viewable_id', <ID HERE>)->delete();
```
