### ISSUE TITLE
Unique count not working for Article Read(NuxtJs + Laravel): using Laravel sanctum Package (Token Based Authentication)

### ISSUE THREAD

**Issue by KamranMaqbool** [cyrildewit/eloquent-viewable#236]
- Eloquent Viewable: #.#.#
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Database Driver & Version: Mysql

### Description:
I'm creating a content management system (create, view, delete article) using Laravel + Nuxt Js 
For Authentication using laravel sanctum Package (TokenBased Authentication)

when I click on to show a single article.in my controller method i use this code
`  $articles = Article::whereNamedId($article_id)->get();
            views($articles[0])->unique()->count();
`
I'm also try this `$articles[0])->record()`
but not return unique count(article view)

#### Expected behavior:
I'm follow all the step that you explain in the documentation but not give the unique visitor count

how can I handle this using your package?

![Screenshot from 2020-09-13 13-31-19](https://user-images.githubusercontent.com/53546053/93013912-d50d4300-f5c5-11ea-8792-0e7fc256a2d0.png)

![Screenshot from 2020-09-13 13-30-21](https://user-images.githubusercontent.com/53546053/93013864-8eb7e400-f5c5-11ea-903b-67ff559840f9.png)

![image](https://user-images.githubusercontent.com/53546053/93013888-aee7a300-f5c5-11ea-9af8-4a10364bd6ab.png)

**Comment by vaibhavpandeyvpz** [comment]
To my observation, I don't think this package works in stateless mode (APIs). I tried using it and had to at last implement custom behavior.

**Comment by KamranMaqbool** [comment]
@vaibhavpandeyvpz please can you share your code?

**Comment by cyrildewit** [comment]
The default way this package remembers a visitor is by a cookie. Since RESTful APIs are stateless, this is not possible. My solution was by levering this functionality to the client-side. This requires a custom Visitor class as described in the [documentation](https://github.com/cyrildewit/eloquent-viewable#custom-information-about-visitor).

If you have any suggestions, please let me know.
