### ISSUE TITLE
Record Landing Page

### ISSUE THREAD

**Issue by farabiandrika** [cyrildewit/eloquent-viewable#239]
- Eloquent Viewable: 5.2.1
- Laravel Version: 8.7.1
- PHP Version: 7.4.6
- Database Driver & Version: MySQL

### Description:

Hey, i want to record my landing page views. My landing page doesn't have a model. It just calling other models with many records. Example Post models, with many records. And i'll show all the records on my landing page. But, in the eloquent-viewable, how can i record my landing page viewer?

This is my landing page(index) function.

![image](https://user-images.githubusercontent.com/38185143/95645119-3f8ea180-0ae6-11eb-926c-c25fd0a7e5af.png)

**Comment by cyrildewit** [comment]
If you want to use this package to keep track of your landing page views, you could create a dedicated `Page` model. Then you can create one record for the landing page and use it as the `Viewable` model.
