### ISSUE TITLE
views($item)->count() ignores records with collection name

### ISSUE THREAD

**Issue by Jellevisser1** [cyrildewit/eloquent-viewable#241]
- Eloquent Viewable: 5.2
- Laravel Version: 8.12.3
- PHP Version: 7.4.9
- Database Driver & Version: MariaDB 10.5.4

### Description:
views($item)->count() or views('App\Models\ModelName')->count() only counts records where the 'collection' field is NULL in the database.

In my case I have a collection for each language an item gets viewed in, and views($item)->collection($locale)->count() works just fine.

#### Expected behavior:
All the records for an item should be counted, regardless of the collection name if no collection is passed with the ->collection() function.

#### Actual behavior:
Only records where the 'collection' field is NULL in the database gets counted when the ->collection function is omitted.

#### Edit:
The orderByViews function works as expected. This function ignores the collections if the 3rd parameter is omitted and thus orders by the total amount of view records, and not by the amount of view records where the collection name is NULL.

**Comment by cyrildewit** [comment]
@Jellevisser1 thanks for explaining your issue in detail. Can't test it right now, but will look into it and fix this behavior in the next major version.
