### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by cidious** [cyrildewit/eloquent-viewable#244]
- Eloquent Viewable: 5.2
- PHP Version: 8.0

### Description:

the latest version of the package requires php: ^7.2 which is not compatible with PHP 8.0

**Comment by mayhemant** [comment]
Yes, please!

![image](https://user-images.githubusercontent.com/74244707/102012050-33d18c80-3d6e-11eb-93e3-1ab057a95275.png)

**Comment by mayhemant** [comment]
cc @cyrildewit

**Comment by cyrildewit** [comment]
I've added support for PHP 8 in the upcoming major version.

**Comment by mayhemant** [comment]
Awesome @cyrildewit 👏🏻

**Comment by cyrildewit** [comment]
I've released `v6.0.0-alpha.1` for anyone needing it fast. Read the changelog and view the comparison. I think it's quite stable.
