### ISSUE TITLE
Get posts with views

### ISSUE THREAD

**Issue by robertnicjoo** [cyrildewit/eloquent-viewable#245]
- Eloquent Viewable: ^5.2
- Laravel Version: 8.21
- PHP Version: 7.4
- Database Driver & Version: 4.5

### Steps To Reproduce:

1. get all posts
2. get each post views included

#### Expected behavior:

Getting list of posts with views count

#### Actual behavior:

I'm not sure how to get views on array

# Explanation

I have following function, which return all of posts

```php
   public function index()
    {
        $posts = Post::orderby('created_at', 'desc')->with(['user', 'tags', 'categories', 'images', 'comments', 'metas', 'likes'])->get();
        return response()->json([
            'data' => PostsResource::collection($posts),
            'message' => 'Posts are ready.'
        ], 200);
    }
```

I need to have posts count included.

like: `->with(['user',........ 'views'])->get();`

**Comment by cyrildewit** [comment]
You can use the `withViewsCount()` query scope on your `Viewable` Eloquent model.

```php
public function index()
    {
        $posts = Post::with(['user', 'tags', 'categories', 'images', 'comments', 'metas', 'likes'])
            ->withViewsCount()
            ->orderby('created_at', 'desc')
            ->get();

        return response()->json([
            'data' => PostsResource::collection($posts),
            'message' => 'Posts are ready.'
        ], 200);
    }
```

It makes use of the native `withCount()` method that's provided by Eloquent. You can see the method code [here](https://github.com/cyrildewit/eloquent-viewable/blob/master/src/InteractsWithViews.php#L92).

**Comment by robertnicjoo** [comment]
@cyrildewit  Thank you.
