### ISSUE TITLE
Cache and views count

### ISSUE THREAD

**Issue by MB116** [cyrildewit/eloquent-viewable#249]
Hi! How can i count views with https://github.com/spatie/laravel-responsecache?

**Comment by cyrildewit** [comment]
Well, the package caches the whole response. So if you want to update the views count on the page, you will have to [clear the cache](https://github.com/spatie/laravel-responsecache#forget-one-or-several-specific-uris).

The controller action will also not be fired, so you will have to move the `record()` functionality to the middleware layer.
