### ISSUE TITLE
Caching view counts cannot be empty

### ISSUE THREAD

**Issue by francoism90** [cyrildewit/eloquent-viewable#250]
- Eloquent Viewable: 6.0.0
- Laravel Version: 8.12
- PHP Version: 7.4.1
- Database Driver & Version: MariaDB

### Description:

 The default value null of the $lifetime argument of the remember method has been removed.

The README still provides empty $lifetime examples and the docblock also seems to allow be incorrect.
Think this is an easy fix. :)

### Steps To Reproduce:

1. Upgrade to V6
2. Use remember()
3. Get error

#### Expected behavior:

Lifetime should be provided.

#### Actual behavior:

Lifetime should be defined error.

**Comment by cyrildewit** [comment]
Should be fixed now.
