### ISSUE TITLE
Field 'id' doesn't have a default value

### ISSUE THREAD

**Issue by robertnicjoo** [cyrildewit/eloquent-viewable#253]
- Eloquent Viewable: ^5.2
- Laravel Version: 8.21
- PHP Version: 7.4
- Database Driver & Version:  4.5

### Description:

I am using `uuid` for `views` table and when I use `views($post)->record();` I get following error

```bash
message: "SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: insert into `views` (`viewable_id`, `viewable_type`, `visitor`, `collection`, `viewed_at`) values (c4a41a90-1274-4830-8974-71d6b5834216, App\Models\Post, tsU9YvlISpc8jQkL42m2OB47SYaT7hbfyshmyeapzkNOlEoMWRMJTOmteoMq7sQUc6D3Vtr8egFuYNbM, ?, 2021-01-04 11:33:35))"
```

### Steps To Reproduce:

1. 
```php
$post = Post::where('slug', $slug)->where('online', true)->first();
if($post){
  views($post)->record();
}
```
2. Generate `uuid`

```php
\Ramsey\Uuid\Uuid::uuid4()->toString()
```

#### Expected behavior:

Add `uuid` instead of default `autoincrement `

#### Actual behavior:

Getting error above.

# Update

I've manually edited `View.php` in vendor folder and added following lines:

```php
use GoldSpecDigital\LaravelEloquentUUID\Database\Eloquent\Uuid; // uuid package i use

class View extends Model implements ViewContract
{
    use Uuid;
    protected $keyType = 'string';
    public $incrementing = false;
    //........
```

It works with this but as we know it's not good solution  (as soon as this package gets update all this settings will be wiped) is there any other solution to this?

**Comment by hasnatwe** [comment]
You need to assign UUID to the id column manually after generating it. The best place is "::creating" model event to assign.
