### ISSUE TITLE
How to get the data of the last 7 days in an array?

### ISSUE THREAD

**Issue by GianlucaScarciolla** [cyrildewit/eloquent-viewable#254]
Hello together!
I wonder how I get the visits of the last 7 days as array. By this I mean that I get the total of each day.
Unfortunately, I could not find anything about it or I overlooked it.

Can someone help me? Thanks a lot already!

**Comment by AbdallaMohammed** [comment]
Hi,
Did you find any answer for this question? as I'm having the same question.

**Comment by cyrildewit** [comment]
@AbdallaMohammed this not provided oit of the box. I would try to write a SQL query that counts the views and group them by date.
