### ISSUE TITLE
Help with error when a 404 is hit. 

### ISSUE THREAD

**Issue by ap-coder** [cyrildewit/eloquent-viewable#256]
- Laravel Version: ^8.0
- PHP Version: 8.0.3
 
- spatie/laravel-missing-page-redirector  ^2.7

### Description:

I use the latest spatie/laravel-missing-page-redirector  to handle my 404  / 301 redirects and everything worked fine. I installed you viewable package to record views and it seemed like everything was working until a bunch of 404 showed up in our search console. 

It seems that your package errors out when a 404 is his with the below error code. Because this happens it prevents the redirect from happeing. 

```php
CyrildeWit\EloquentViewable\Views::forViewable(): Argument #1 
($viewable) must be of type CyrildeWit\EloquentViewable\Contracts\Viewable, null given, called in /var/www/vhosts/codecorp/releases/20210601223001/vendor/cyrildewit/eloquent-viewable/src/helpers.php on line 26
{"userId":2,"exception":"[object] (TypeError(code: 0): CyrildeWit\\EloquentViewable\\Views::forViewable(): Argument #1 ($viewable) must be of type CyrildeWit\\EloquentViewable\\Contracts\\Viewable, null given, called in 
/var/www/vhosts/codecorp/releases/20210601223001/vendor/cyrildewit/eloquent-viewable/src/helpers.php on line 26 at 
/var/www/vhosts/codecorp/releases/20210601223001/vendor/cyrildewit/eloquent-viewable/src/Views.php:61)

```
 
Can you please tell me how to prevent this from happeing if the view does not exist please.  You help would be very appreciated.

**Comment by cyrildewit** [comment]
Can you also post the code that you're using? The reason why this exception is thrown, is because you can't save a view for an unsaved model. An unsaved model does not contain a unique identifier, which is required to make the link with the viewable Eloquent model.
