### ISSUE TITLE
Getting an error: Cannot record a view for a viewable type.

### ISSUE THREAD

**Issue by chintakdholakia** [cyrildewit/eloquent-viewable#258]
- Eloquent Viewable: 6.0.2
- Laravel Version: 8.53.1
- PHP Version: 8.0.x
- Database Driver & Version:

### Description:
Getting this error: CyrildeWit\EloquentViewable\Exceptions\ViewRecordException
Cannot record a view for a viewable type.

### Steps To Reproduce:

1. Open the page where the Record tag is stored in the controller.

**Comment by cyrildewit** [comment]
It means that your model is not saved to the database before you pass it in the `views()` function. You can't record a view for a viewable type. It must exists first.
