### ISSUE TITLE
user id instead of cookie

### ISSUE THREAD

**Issue by mohammad6006** [cyrildewit/eloquent-viewable#259]
- Eloquent Viewable: 6.0
- Laravel Version: 8.12
- PHP Version: 7.4
- Database Driver & Version:

### Steps To Reproduce:

I use API and because of that unique function doesn't work.

I decided to store user id instead of cookie

I pass user from apicontroller:
```
            $user = Auth::user();
            views($news)->viewedBy($user)->record();

```

I create a custom Views Model:

```
class Views extends \CyrildeWit\EloquentViewable\Views
{
    protected $viewer;    

    public function viewedBy(User $user)
    {
        $this->viewer = $user;
        return $this;
    }
    /**
     * Create a new view instance.
     *
     * @return \CyrildeWit\EloquentViewable\Contracts\View
     */
    protected function createView(): ViewContract
    {
        $viewer = $this->viewer;

        $view = Container::getInstance()->make(ViewContract::class);

        return $view->create([
            'viewable_id' => $this->viewable->getKey(),
            'viewable_type' => $this->viewable->getMorphClass(),
            'visitor' => $viewer->id,
            'collection' => $this->collection,
            'viewed_at' => Carbon::now(),
        ]);
    }

}

```
The problem is that `$viewer->id` return null

#### Expected behavior:

`$user` or `$this->viewer` return user info in viewdBy method but return null in createView method

**Comment by cyrildewit** [comment]
@mohammad6006 were you testing the API endpoint with Postman? This might have caused the views not being saved, because Postman is recognized as a crawler. You can change the agent in Postman I believe.
