### ISSUE TITLE
how can I get user post view count 

### ISSUE THREAD

**Issue by Elusoji** [cyrildewit/eloquent-viewable#261]
so I have I tired doing something  like this post has eloquent-viewable package but user does not 
but user has a relationship with post so I think if I try it this way it might work 

 `views($user->posts)->count()`

not working

**Comment by cyrildewit** [comment]
Hey @Elusoji,

Let's first address the issue with your code example. What kind of type does the global `views(....)` helper expect? See the source code (hint start by looking at helpers.php file) to find out.

Once you understand this, we can try find a solution to your problem/feature.

Greetings
