### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by VincentVanWijk** [cyrildewit/eloquent-viewable#264]
- Eloquent Viewable: 6.0.2
- Laravel Version: 9.0
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 5.7

### Description:
Upgrading to Laravel 9 fails on `composer update`

### Steps To Reproduce:
1. follow the upgrade guide at : [upgrade guide](https://laravel.com/docs/master/upgrade)
2. run `composer update`

#### Expected behavior:
all packages are succesfully installed / upgraded

#### Actual behavior:
composer returns the following error:
![image](https://user-images.githubusercontent.com/10919865/153190625-8828a87d-eddd-45f3-ba1c-e887f0b7fbe6.png)

**Comment by davisriska** [comment]
+1 Also waiting on the update so I can upgrade to L9

**Comment by atmonshi** [comment]
PR open: #265

**Comment by DanielRTRD** [comment]
+1

**Comment by melchiot** [comment]
+1

**Comment by cyrildewit** [comment]
Hey,

I've released #265 yesterday under the version name `v6.1.0`. My apologies, but I'm really busy these days.
