### ISSUE TITLE
Error : Cannot record a view for a viewable type

### ISSUE THREAD

**Issue by oussamanm** [cyrildewit/eloquent-viewable#267]
- Eloquent Viewable: #.#.#
- Laravel Version: 8.79.0
- PHP Version: 8.0.#
- Database Driver & Version: Mysql 10.4

### Description:
i just tried to use this package i followed every step on the Documentation , but i still can't make it work .
i get the following Error: 
`
CyrildeWit\EloquentViewable\Exceptions\ViewRecordException
Cannot record a view for a viewable type.
`

### Steps To Reproduce:

1. My model :

```
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use CyrildeWit\EloquentViewable\Contracts\Viewable;


class Store extends Model implements Viewable
{
    use InteractsWithViews;
    //use HasFactory;
}
```

3. MyController :

```
namespace App\Http\Controllers\Web;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Store;

class storeController extends Controller
{    
    public function index(Store $store)
    {        
         views($store)->cooldown($minutes = 3)->record();
          
         return view('web.home', ['title' => trans('admin.Store')]);
    }
}
```

#### Actual behavior:

Error , not working

**Comment by cyrildewit** [comment]
Hey @oussamanm , if you read the error message you would have found out that the value you provide to the `view($model)` helper is not an instance of an existing model. It's probably `null`.
See for yourself by dumping the value of `$store`, before anything else.

Hope this will help you.
