### ISSUE TITLE
How to add some fields to table views

### ISSUE THREAD

**Issue by adnanerlansyah403** [cyrildewit/eloquent-viewable#273]
Hello sir, I want to ask. How to add some fields to table views like add ip_address or agent_user and etc. because the default in table views does not provide it? 

Thanks sir.

**Comment by cyrildewit** [comment]
Hey @adnanerlansyah403 , 

You can create you own database migration to adjust the views table. You're free to modify it at any time. To extend the package, you find find some help at the extending section in the documentation.
