### ISSUE TITLE
cannot use CyrildeWit\EloquentViewable\Contracts\Viewable - it is not a trait

### ISSUE THREAD

**Issue by eymeen** [cyrildewit/eloquent-viewable#276]
- Eloquent Viewable: 6.1.0
- Laravel Version: 8.83.19
- PHP Version: 8.1.6

### Description:
I want to set viewable to article model, I downloaded everything and shared things in the installation. I'm getting this error back `App\Models\Article cannot use CyrildeWit\EloquentViewable\Contracts\Viewable - it is not a trait` 

Article Model:
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use CyrildeWit\EloquentViewable\Contracts\Viewable;

class Article extends Model
{
    use HasFactory, Viewable;

    protected $fillable = [
        'title',
        'slug',
        'keywords',
        'description',
        'image',
        'body',
        'views',
    ];
}
```

**Comment by cyrildewit** [comment]
Please read the documentation carefully. `Viewable` is na interface not a trait. The trait is `InteractsWithViews`.
