### ISSUE TITLE
Class "Period" not found

### ISSUE THREAD

**Issue by Rinaldi100** [cyrildewit/eloquent-viewable#278]
- Eloquent Viewable: Period
- Laravel Version: 9.11
- PHP Version: 8.1

### Description:
i found error 'Class "Period" not found'

### On Model
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use CyrildeWit\EloquentViewable\Contracts\Viewable;

    class Hotel extends Model implements Viewable

    {
              use HasFactory, Sluggable, InteractsWithViews;
                 ...
    }

### On Controller

    public function hotelDetail($slug)

    {
        $hotels  = Hotel::with('room', 'getprovince')->where('slug', $slug)->first();

        views($hotels)->record();

        return view('frontend.hotel.hotel-detail', compact('hotels'));
    }

### On Views

 {{views($hotels)->period(Period::since('2022-10-14'))->count();}}
                                      

#### Expected behavior:

How to fix them

**Comment by cyrildewit** [comment]
Hi,

You forgot to import the Period class from the correct namespace. See https://github.com/cyrildewit/eloquent-viewable#get-views-count-of-a-specific-period

Add `use CyrildeWit\EloquentViewable\Support\Period;` at the top to the import lines. Right now your application is trying to use the Period class from the global namespace.

**Comment by Rinaldi100** [comment]
oh yes i see, thanks a lot bro..
