### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by prof-usman** [cyrildewit/eloquent-viewable#283]
Please add support for Laravel 10

**Comment by mperezsc** [comment]
Hello!
Will this come at some point?
Thanks a lot for the package

**Comment by cyrildewit** [comment]
Hey,

If someone can fix the issues in the master branch (specially the integration tests) then I can release a new version.

I'm not in the position at the moment to work on this project due to other responsebilities (work and study).

Feel free to contribute
