### ISSUE TITLE
How to extend the package to also count other things

### ISSUE THREAD

**Issue by bumpyy** [cyrildewit/eloquent-viewable#289]
Is there a way to extend the package to count other things like share, so i can count view and share click ?

**Comment by cyrildewit** [comment]
Doesn't sound like a good thing to do. You could copy most of the logic from this package and build it yourself. Keep it simple. Extending this package to that advance will make it more entangled.

I think the shares will also be stored in a different structure.

**Comment by cyrildewit** [comment]
Good luck.
