### ISSUE TITLE
Record Unique Visit

### ISSUE THREAD

**Issue by fanalis93** [cyrildewit/eloquent-viewable#293]
I am trying to record only unique IP visit.
For example, if IP-1 visits a post three or whatever times, it should record only once for that IP and specific post. If the IP visits another post, then record once for that post. 
I noticed package stores visitor cookie key each time it visits and they are different everytime so it's confusing how to record uniquely.

I couldn't find any method for that? How should I approach this?

**Comment by cyrildewit** [comment]
There is no solution out of the box available, but I believe that all the neccessary abilities are available to make a solution for your problem. Here's some inspiration:

Don't forget that you can still use all the features from Eloquent. 

**1. Create a custom implementation for Visitor instance to use the IP address as Visitor ID**

The default strategy uses a cookie based solution to identify visitors which holds a random string. This string is stored as the visitor ID per view, which can then be used to make the unique views count. If you want to alter this strategy to use the IP addresses of visitors to distinguish unique views, then you could create your own Visitor implementation where the id() method returns the IP address instead. More information on this can be found here: https://github.com/cyrildewit/eloquent-viewable/tree/master?tab=readme-ov-file#create-your-own-visitor-class

Be sure that the IP address that you use is the actual IP address of the visitor and not the IP address of your server. 

**2. Only store a view if the IP address is unique**

You could check yourself if you should actually record the view based on the known views and IP address.

```php
$ipAddressAlreadyViewedViewable = true|false; // Database query that checks if the IP address already viewed the post

if ($shouldRecordView) {
    views(..)->record();
}
```
