### ISSUE TITLE
Problem installing with Laravel 11 and PHP 8.2

### ISSUE THREAD

**Issue by kgp43** [cyrildewit/eloquent-viewable#298]
- Eloquent Viewable: 7.0.2
- Laravel Version: 11.2.0
- PHP Version: 8.2.12
- Database Driver & Version: 10.4.32-MariaDB

### Description:

Getting error  when trying to install using Laravel 11 and PHP 8.2

### Steps To Reproduce:

composer require cyrildewit/eloquent-viewable

#### Expected behavior:

[What you expected to happen]

#### Actual behavior:

composer require cyrildewit/eloquent-viewable

./composer.json has been updated
Running composer update cyrildewit/eloquent-viewable
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cyrildewit/eloquent-viewable[v0.1.0, ..., v0.1.7, v1.0.0, ..., v1.0.5] require nesbot/carbon ^1.22 -> found nesbot/carbon[1.22.0, ..., 1.39.1] but the package is fixed to 3.2.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - cyrildewit/eloquent-viewable[v2.0.0, ..., v2.5.0] require php ^7.0 -> your php version (8.2.12) does not satisfy that requirement.
    - cyrildewit/eloquent-viewable[v3.0.0, ..., v3.2.0, v4.0.0, ..., v4.1.1] require php ^7.1 -> your php version (8.2.12) does not satisfy that requirement.
    - cyrildewit/eloquent-viewable[v5.0.0, ..., v5.2.1] require php ^7.2 -> your php version (8.2.12) does not satisfy that requirement.
    - cyrildewit/eloquent-viewable[v6.0.0, ..., v6.0.2] require illuminate/cache ^6.0|^7.0|^8.0 -> found illuminate/cache[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - cyrildewit/eloquent-viewable v6.1.0 requires illuminate/cache ^6.0|^7.0|^8.0|^9.0 -> found illuminate/cache[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - cyrildewit/eloquent-viewable v7.0.1 requires illuminate/cache ^6.0|^7.0|^8.0|^9.0|^10.0 -> found illuminate/cache[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.7] but these were not loaded, likely because it conflicts with another require.
    - cyrildewit/eloquent-viewable v7.0.2 requires nesbot/carbon ^2.0 -> found nesbot/carbon[2.0.0, ..., 2.72.3] but the package is fixed to 3.2.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires cyrildewit/eloquent-viewable * -> satisfiable by cyrildewit/eloquent-viewable[v0.1.0, ..., v0.1.7, v1.0.0, ..., v1.0.5, v2.0.0, ..., v2.5.0, v3.0.0, ..., v3.2.0, v4.0.0, v4.1.0, v4.1.1, v5.0.0, v5.1.0, v5.2.0, v5.2.1, v6.0.0, v6.0.1, v6.0.2, v6.1.0, v7.0.1, v7.0.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require cyrildewit/eloquent-viewable:*" to figure out if any version is installable, or "composer require cyrildewit/eloquent-viewable:^2.1" if you know which you need.

**Comment by abedcodes** [comment]
so what to do?

**Comment by kgp43** [comment]
> so what to do?

Have to wait until they fix it I guess :)

**Comment by cyrildewit** [comment]
I released v7.0.3. Allowing Carbon v3 should do the trick.

**Comment by abedcodes** [comment]
Thanks for your time, this is a powerful package with very simple api 👍
