### ISSUE TITLE
I can not install it

### ISSUE THREAD

**Issue by MarceloBonifazio** [cyrildewit/eloquent-viewable#64]
I'm following the [tutorial](https://github.com/cyrildewit/laravel-page-view-counter#installation).

But in cmd I get the following answer:

> Nothing to publish for tag [migrations].

```
C:\Users\projectl>composer require cyrildewit/laravel-page-view-counter
Using version ^1.0 for cyrildewit/laravel-page-view-counter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing cyrildewit/laravel-page-view-counter (v1.0.5): Downloading (100%)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled class file has been removed.

C:\Users\projectl>php artisan vendor:publish --provider="CyrildeWit\PageViewCounter\PageViewCounterServiceProvider" --tag="migrations"
Nothing to publish for tag [migrations].
```

In `config/app` I already inserted the provider

`CyrildeWit\PageViewCounter\PageViewCounterServiceProvider::class,`

**Comment by cyrildewit** [comment]
Before doing the following, please check if the migration has been already published.

Do you have a class named `CreatePageViewsTable` in your application? You can do a simple check with `class_exists('CreatePageViewsTable')`.

Try to remove the if statement in the `PageViewCounterServiceProvider` at line: `30` in the vendor directory and  rerun:

```winbatch
php artisan vendor:publish --provider="CyrildeWit\PageViewCounter\PageViewCounterServiceProvider" --tag="migrations"
```

**Comment by MarceloBonifazio** [comment]
The check `class_exists('CreatePageViewsTable')` return false

I remove the if statement `if (! class_exists('CreatePageViewsTable')) {` in vendor directory but the same problem occurs.

**Comment by cyrildewit** [comment]
Perhaps you have to clear the config cache by running `php artisan config:clear`.

**Comment by cyrildewit** [comment]
@MarceloBonifazio did clearing the config cache solved your problem?
