### ISSUE TITLE
Have you removed the viewThatExpiresAt trait from this? 

### ISSUE THREAD

**Issue by SqrFactor** [cyrildewit/eloquent-viewable#69]
// Store a new page view into the database with an expiry date
$article->addPageViewThatExpiresAt(Carbon::now()->addHours(3));

Have you removed this? or Is there a different way of doing it?

- Eloquent Viewable: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Steps To Reproduce:

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior:

[What you expected to happen]

#### Actual behavior:

[What actually happened]

**Comment by cyrildewit** [comment]
I don't really have a good reason for it, but I decided not to add it to the second version. I'm open to the idea of bringing it back.

**Comment by zymawy** [comment]
It's one of the useful Trait Hopefully, You Can Keep it.

**Comment by SqrFactor** [comment]
I would really love it, if you can add the trait. The only reason I'm not able to migrate to v2.0 is because I want my view count that way. Let me know, if you can add it and till when? 

Thanks :+1:

**Comment by cyrildewit** [comment]
I've created a dedicated issue for this feature #70.
