### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by paparyku** [cyrildewit/eloquent-viewable#72]
Support for mongodb plugin for laravel
https://github.com/jenssegers/laravel-mongodb

benifits on using mongodb over mysql is no need to make annoying migrations just add the data with eloquent as you go.

**Comment by cyrildewit** [comment]
I needed some time to think about it, but I don't think I want to implement this feature into this package. It's really project specific. However, this is the perfect case to use the **extending** feature. The documentation for this can be found at: https://github.com/cyrildewit/eloquent-viewable#extending

This feature gives you the ability to override some of the core classes with your own implementation.

For your case, you will probably have to override the `View` model and the `ViewableService`.
