### ISSUE TITLE
Migrating data from v1.0 databse to v2.0 | Also, how is it different compared to v1.0 

### ISSUE THREAD

**Issue by SqrFactor** [cyrildewit/eloquent-viewable#75]
Hi Cryril, 

I hope you are doing good. Thank you for adding the viewThatExpiresAt trait in the v2.0 but my question here is what is the difference between v2.0 and v1.0 and how do I migrate my older v1.0 data to new v2.0 as the table structure is different this time?

**Comment by cyrildewit** [comment]
@SqrFactor

> what is the difference between v2.0 and v1.0

In version `1.0` the structure for the `page-views` table is as follows:

```php
$table->increments('id');
$table->bigInteger('visitable_id')->unsigned();
$table->string('visitable_type');
$table->string('ip_address')->nullable();
$table->timestamps();
```

The `id` column remains the same.

The `visitable_id` and `visitable_type` column also remains the same, but the code is simplyfied by using the `->morphs` helper.

The `ip_address` column has been renamed to `visitor` and it's not nullable anymore.

The timestamps helper creates two columns: `created_at` and `updated_at`. I've removed the `updated_column` and renamed the `created_at` column to `viewed_at`.

Here's the new table structure for `v1`:

```php
$table->increments('id');
$table->morphs('viewable');
$table->string('visitor');
$table->timestamp('viewed_at')->useCurrent();
```

I thought I had created a ready to use migration, to upgrade from `v1` to `v2`, but that isn't the case. I experimented with creating one this morning, but I had some trouble with my database. I will try to get it working and add it to the upgrade guide.

> how do I migrate my older v1.0 data to new v2.0

When I have created the ready to use migration, you can download it and add it to your `database/migrations`. Then you can run `php artisan migrate`.

Regards,
Cyril

**Comment by cyrildewit** [comment]
I've created the following migration to upgrade from v1 to v2: https://github.com/cyrildewit/eloquent-viewable/blob/2.1/resources/database/migrations/2018_06_07_311156_update_views_table.php

I'll let the decision to split it into multiple migrations up to you.

If you're on prodcution, please backup your database before running the migration.

**Comment by SqrFactor** [comment]
Hi, 

Can you please elaborate on the complete steps of migrating the older database into new. Do I have to create a new migration table update_views_table.php and then add the Schema code from there onward? Let me know. 

Best, 
Agnim
