### ISSUE TITLE
getting viewable_id null on $model->addView();

### ISSUE THREAD

**Issue by sagar55666** [cyrildewit/eloquent-viewable#83]
- Eloquent Viewable: "cyrildewit/eloquent-viewable": "^2.1",
- Laravel Version: "laravel/framework": "5.6.*",
- PHP Version: "php": "^7.1.3",
- Database Driver & Version: mysql

### Description:
On my local machine I have installed it and migration with the view table is done successfully but calling the model on my post details controller function as below.

public function getPostDetail(Post $post){
       $post->addView();
}
giving me error of viewable_id null so not able to store the views in the database. please check below refer for the error.
Refer: http://prntscr.com/k4pjcn

**Comment by cyrildewit** [comment]
Can you show me the code that defines the route for this controller method?

**Comment by Youssef20000** [comment]
I Have The Same Issue

**Comment by armagedan** [comment]
Please check if you are getting an IP Address by using `return $request->ip()`. If you are getting a null result, that is the issue. You will have to add `Request $request` to your function where it says and similar to `Post $post`.

Also check and see if you have the cookie setup and allowed.

**Comment by cyrildewit** [comment]
This error probably appear due to wrong route model binding.

If the `$post` variable contains an empty `Post` model, the `addView` method will get `null ` when calling `$post->getKey()`.

**Comment by armagedan** [comment]
You’re most welcome. Glad I could help. Love this package so far! 
It is true. Probably a null result set. Or an issue with cookie or the IP address being null.
