### ISSUE TITLE
How can I count multiple views setup

### ISSUE THREAD

**Issue by armagedan** [cyrildewit/eloquent-viewable#84]
First off, love the package and what you’ve done with it so far.
The issue for me is that I have 2 variables which handles 2 kinds of views. One of the route is as follows:
 
    Route:get(‘post/{category}/{id}’, ‘SomeController@Display’);

And here is the second route: 

    Route:get(‘post/{category}/{subcategory}/{id}’, ‘SomeOth rController@Display’)

As you can see, I have one controller and route which displays post with category. The other route and controller is for sub category. They both come from the same model. They also have different where clauses. 

So my question is, in this case, should I use the same method as in the docs? I mean, should I use the $post->addView(); on both the controller display method?

And if so, how can I get the count of these two separately? One is with category. The other one with sub category.
Lastly, how can I order these two by whats the most popular posts. The issue for me is that I am using a category and subcategory separately. So if I want to even count the views, I would want to count it for category and subcategory. Those two are having 2 routes and two methods. That’s my confusion.

**Comment by cyrildewit** [comment]
This feature is currently not supported. I have scheduled this for the next major version.

**Comment by armagedan** [comment]
This issue has been resolved. I misunderstood the package previously. Please close the issue :)

**Comment by armagedan** [comment]
This issue has been resolved. It was a misunderstanding from my side :)

**Comment by cyrildewit** [comment]
I know, but I like the idea to have multiple counters ;).

**Comment by armagedan** [comment]
Meaning something like this?

`$post->getViews()`
`$post->myownGetViews()`

A custom tag?

**Comment by cyrildewit** [comment]
Something like this `$post->addView(string $tag)`. `$post->getViewsByTag(string $tag)`.

It's just an idea.

```php
// using a facade

Views::create($viewable, string $tag)->addView(); // save new view
Views::create($viewable, string $tag);->getViews() // get the views count 
```

**Comment by armagedan** [comment]
I see. A string parameter for a tag. Nice. Love the idea :)

**Comment by gjsman** [comment]
@cyrildewit Any progress on this?

**Comment by cyrildewit** [comment]
@gjsman I will implement this feature in `v3`!

**Comment by cyrildewit** [comment]
Would it be okey if I use `spatie/laravel-tags` under the hood to acomplish this feature?

**Comment by armagedan** [comment]
I certainly do not see an issue with using this. It’s a handy package too. For taggables.

**Comment by cyrildewit** [comment]
I decided to keep it simple for now, so multiple tags isn't supported. I also decided to use the word `collection` to describe the feature instead of `tag`.

**From the documentation:**

If you have different types of views for the same viewable type, you may want to store them in their own collection.

```php
views($post)
    ->collection('customCollection')
    ->record();
```

To retrieve the views count in a specific collection, you can reuse the same `collection()` method.

```php
views($post)
    ->collection('customCollection')
    ->count();
```

**Comment by cyrildewit** [comment]
@armagedan @gjsman thank you for giving your opinion!
