### ISSUE TITLE
Does this package not use cookies?

### ISSUE THREAD

**Issue by armagedan** [cyrildewit/eloquent-viewable#85]
I know it does use cookies but every time i refresh the post page and go back, it is added as a view to the db. The expected behavior is that the user should only be able to view one single post once. Unless the cookie is deleted and browser is refreshed. In that case, a new view will be added. Or am I doing something wrong here?

**Comment by cyrildewit** [comment]
The reason why this package stores every view in the database, instead of only the unique ones, because I wanted to have both numbers. All views an unique views.

**Comment by armagedan** [comment]
Hello,

How can I store a unique view? Can this be possible with cookie? Because
currently it is a big flaw for my app as users and able to refresh multiple
times and keep adding views. Can I use cookies to store unique views and
count? But also keep all the other functions (like the popular order by and
so on). Just want to be able to use unique views.

**Comment by cyrildewit** [comment]
You can use the `getUniqueViews` method. This method filters out all the unique views.

**Comment by armagedan** [comment]
Solved. Like I mentioned earlier on issue #88, the orderByViewsCount() should be able to take unique view counts. For anyone who stumbles across this, please review #88 as mentioned above.

**Comment by cyrildewit** [comment]
I released `v2.3.0` with the available `orderByUniqueViewsCount`.

**Comment by armagedan** [comment]
Thanks a bunch :) I will have a look at this in a while and report back to you 👍
