### ISSUE TITLE
$sortedPosts = Post::orderByViewsCount()->get();

### ISSUE THREAD

**Issue by kenfu** [cyrildewit/eloquent-viewable#86]
- Eloquent Viewable: 2.1.0
- Laravel Version: 5.5.28
- PHP Version: 7.1.0
- Database Driver & Version:

### How use Period?
Class 'App\Http\Controllers\Period' not found

### Can I use orderByViewsCount like getViews

```php
$sortedPosts = Post::orderByViewsCount(Period::subDays(7))->get();
```

I need a POST weekly click list... 

PS：My English is very poor, sorry

**Comment by Xoshbin** [comment]
It's giving me this error:

> Argument 2 passed to App\Post::scopeOrderByViewsCount() must be of the type string, object given, called in 
and that's my code:
`$posts = Post::orderByViewsCount(Period::subDays(7))->get();`

**Comment by cyrildewit** [comment]
Ooo, this code is wrong: `Post::orderByViewsCount(Period::subDays(7))->get();`. The first argument should be `desc` or `asc`. It can't be a period instance.

**Comment by cyrildewit** [comment]
> I need a POST weekly click list...

I think this issue has something similiar: https://github.com/cyrildewit/eloquent-viewable/issues/59
