### ISSUE TITLE
addViewWithExpiryDate() does not exists (anymore)

### ISSUE THREAD

**Issue by francoism90** [cyrildewit/eloquent-viewable#87]
- Eloquent Viewable: 2.1
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: MySQL 8

### Description:
Has been removed? Only `addView()` seems to be available.

### Steps To Reproduce:

Add steps of README

#### Expected behavior:

Is `addView()` doing the same and is `addViewWithExpiryDate()` not needed anymore?

#### Actual behavior:

Doesn't exists.

**Comment by cyrildewit** [comment]
I had bring this feature back to `v2.1.0`, but I apparently made a mistake, so the release does not contain anything. I'm working on it.

**Comment by cyrildewit** [comment]
I released a new minor version that contains the desired feature. Thank you for reporting.

See https://github.com/cyrildewit/eloquent-viewable/releases/tag/v2.2.0

**Comment by francoism90** [comment]
@cyrildewit Many thanks for the update. :)

**Comment by cromartie1984** [comment]
It still do not exist on packagist....

**Comment by cyrildewit** [comment]
@cromartie1984 which version of this package do you have installed?

For `v3` you can use `->delayInSession(...)` [see docs](https://github.com/cyrildewit/eloquent-viewable#recording-views-with-session-delays)

And for `v2` you can use `$model->addViewWithExpiryDate(...)` [see docs](https://github.com/cyrildewit/eloquent-viewable/tree/2.x#saving-views-with-expiry-date)

**Comment by cromartie1984** [comment]
i use the 3.2, thx it works
