### ISSUE TITLE
Column 'visitor' cannot be null

### ISSUE THREAD

**Issue by armagedan** [cyrildewit/eloquent-viewable#88]
This happens when I clear my Cache and Cookies from the browser and refresh the browser.
I get the error `Integrity Violation Column 'visitor' cannot be null`. 
But if I refresh again, It works.

Could it be that the cookie is not being initiated? How can I fix this?

**Comment by cyrildewit** [comment]
I'm not able to reproduce this. I cleared my cache using `php artisan cache:clear` and resetted my browser data in chrome using: at `Application` tab under `Clear storage `-> `clear site data`.

**Comment by armagedan** [comment]
Sorry yes. I had a custom func written because my live server was running on a load balancer and fideloper proxy was not working for some reason. Basically it overrides the $request->ip() function. That is why when I am on my local development, it returns null. Sorry about that. You can close the issue. 

One thing that i did not get was, how do I add unique views? And how do i get popular posts where unique id?

**Comment by cyrildewit** [comment]
> One thing that i did not get was, how do I add unique views? And how do i get popular posts where unique id?

Every time when the `$model->addView()` method is triggered, it stores a view in the database. This view contains the viewer's unique id or his ip address if he's in igcognito mode. You can call the `getUniqueViews` method to get the total number of unique views.

**Comment by armagedan** [comment]
Yes that is fine. But how can I use orderByViewsCount() with unique views?

**Comment by cyrildewit** [comment]
Ahh, I misunderstood. It's currently not possible. Lol, I never thought of that. I'm working on it. There will be a new release soon.

**Comment by armagedan** [comment]
Well. Guess that solves this issue. When is the estimated release?

**Comment by cyrildewit** [comment]
I hope this evening.

**Comment by armagedan** [comment]
Not sure what time that would be for me but I will surely keep hitting that reload button for the new update. By the way, awesome package. Just this feature was what I needed. Keep up the awesome work :)

**Comment by cyrildewit** [comment]
Thank you for the kind words.

I'm not going to make it today. I'm also not really experienced with sql, so it's going to take a while before I found the right query that I can use. I'm busy this week, but I'll try to make it as fast as possible.

**Comment by cyrildewit** [comment]
See #85
