### ISSUE TITLE
[3.0] [RFC] Which features are missing? And should be added to the next major version

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/eloquent-viewable#89]
I'm trying to make up a list of features the next major version should contain. Improvements and changes are also welcome.

Please share your idea and vote using the 👍 and 👎. 

Thanks!

### Potential

- Rename `addView` to `viewed`

### Accepted

- Custom tags (#84)
- Remove IP address as fallback to unique visitor id

**Comment by SaurabhKharivale** [comment]
I just discovered this package today and plan to use it my next project. While I was tinkering with the package I noticed that it uses only uses IP address to determine unique views.

Unique count will not be accurate under following conditions.
1. User who are sharing a machine but have different accounts should be treated as separate views.
2. Users who use DHCP (i.e IP address is not static and is shared by different users which is controlled by their ISP).

Storing **user id** along with **IP address** should help in getting more accurate unique count.

**Comment by SaurabhKharivale** [comment]
Deprecate **addView** method and rename it to use more semantically correct **viewed** method

```
public function show(Post $post)
{
    $post->viewed();

    return view('blog.post', compact('post'));
}
```

**Comment by cyrildewit** [comment]
Thank you for taking the time to write these comments. I really appreciate it.

About your first comment: This package actually uses a random string that's stored inside a cookie on the user's computer (since `v2.0.0`). It will store the user's Ip address if the cookie doesn't exits. I'm hinking about removing this fallback and just store a `null`, so that it doesn't get counted as a unique view.

**Comment by armagedan** [comment]
Replying to the above comment: That is right. Adding a null meaning no one can count it as a unique view ever. Using IP Address has its own flaw. The flaw being, a person on different networks will be able to store their IP hence a new unique ID every time. And what about people on proxy or people who would change their IP. I think the solution above is better as leaving a null will not let anyone store a unique view.

Also one more thing. Is the random string used to store/make cookie using laravel? If so, We do not have to worry about anyone altering the cookie as laravel will not accept altering the cookie value or such.

Thanks for the package.

**Comment by cyrildewit** [comment]
> Also one more thing. Is the random string used to store/make cookie using laravel? If so, We do not have to worry about anyone altering the cookie as laravel will not accept altering the cookie value or such.

The random string is generated using `str_random(80)`. When the `addView` method is triggered it will try to get this random string from a cookie called `eloquent_viewable`. Laravel encrypts this value if I'm right. If this cookie doesn't exists it will fallback to IP.

https://github.com/cyrildewit/eloquent-viewable/blob/2.x/routes/eloquent-viewable.php

https://github.com/cyrildewit/eloquent-viewable/blob/2.x/src/ViewableService.php#L197

I tried to change this cookie's value and view a page. Instead of accepting it, it used my ip address.

**Comment by armagedan** [comment]
Ok so Laravel is not letting the cookie go through because the client/end user altered it. That is why it is going for IP fallback because how it understands it, the cookie does not exist.

**Comment by cyrildewit** [comment]
Correct

**Comment by armagedan** [comment]
Your suggestion is better. Remove IP fallback and enter a null. Because of the above mentioned reasons.

**Comment by cyrildewit** [comment]
I'm going to add it to the to do list. Thanks for the discussion.

**Comment by armagedan** [comment]
No problem :)
